// make sure the answers are all in lower case

// user answers are not case sensitive
// exact question: user must enter the exact answer - answer must be a string
// match question: user must enter the answer word within their answer - answer must be an array
// required: number of keywords required for match question (any over this they are given extra points for)

var topics = ["hardware", "logic", "communication", "data", "software", "misc", "security", "impacts", "misc2", "html", "greenfoot", "assembly", "algorithms"];

var data  = {
	hardware: [
		{
			question: "I need a storage device that has a high capacity, is small, and will not likely break. <br> A: Optical storage <br> B: ROM <br> C: Magnetic storage <br> D: Solid-state storage",
			answer: "d",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "I need a storage device that is portable, cheap, and cannot be overwritten. <br> A: Magnetic storage <br> B: Optical storage <br> C: Solid-state storage <br> D: Pen-and-paper storage",
			answer: "b",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "I need a storage device that has a high capacity, is fast to access, and is cheap to manufacture. <br> A: Solid-state storage <br> B: RAM <br> C: Magnetic storage <br> D: Optical storage",
			answer: "c",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "Which is <strong>not</strong> an example of a device which uses embedded systems? <br> A: Wi-fi router <br> B: Microwave oven <br> C: Laptop <br> D: Blood pressure reader",
			answer: "c",
			answerType: "exact",
			topic: "embedded systems",
		},
		{
			question: "Why are embedded systems used? <i>more answers give you more points</i>",
			answer: [["size", "small"], ["cost", "cheap", "price"], "automatic", "function"],
			answerType: "match",
			required: 1,
			topic: "embedded systems",
		},
		{
			question: "Which is <strong>not</strong> required for <strong>all</strong> computer systems? <br> A: Screen <br> B: Operating system <br> C: Motherboard <br> D: Memory",
			answer: "a",
			answerType: "exact",
			topic: "misc hardware",
		},
		{
			question: "What are the factors that affect the performance of my CPU? <i>more answers give you more points</i>",
			answer: ["cache","clock speed","number of cores"],
			answerType: "match",
			required: 1,
			topic: "cpu cycle",
		},
		{
			question: "What are the <strong>two</strong> types of processors?",
			answer: ["risc","cisc"],
			answerType: "match",
			required: 2,
			topic: "risc and cisc",
		},
		{
			question: "What are the <strong>two</strong> parts of an instruction in assembly language?",
			answer: ["opcode","operand"],
			answerType: "match",
			required: 2,
			topic: "assembly language",
		},
		{
			question: "Which part of an instruction, <strong>opcode or operand</strong>, is the instruction to be carried out by the CPU?",
			answer: "opcode",
			answerType: "exact",
			suddenDeath: true,
			topic: "assembly language",
		},
		{
			question: "Which part of an instruction, <strong>opcode or operand</strong>, is the data to be executed by the instruction?",
			answer: "operand",
			answerType: "exact",
			suddenDeath: true,
			topic: "assembly language",
		},
		{
			question: "What are the <strong>three</strong> parts of a CPU cycle?",
			answer: ["fetch","decode","execute"],
			answerType: "match",
			required: 3,
			topic: "cpu cycle",
		},
		{
			question: "What is hardware?",
			answer: ["physical"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "What are the registers of a CPU (their abbreviations)? <i>more answers give you more points</i>",
			answer: ["acc","mar","mdr","pc"],
			answerType: "match",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "What are the <strong>four</strong> components of a CPU?",
			answer: [["arithmetic logic unit", "alu"], "registers", "internal memory", ["control unit", "cu", "controller"]],
			answerType: "match",
			required: 4,
			extraTime: 0.5, // half speed
			topic: "cpu architecture",
		},
		{
			question: "Which type of CPU data storage is fastest to access?",
			answer: ["register"],
			answerType: "match",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "Which part of the CPU is represented by: <img src='./assets/alu.PNG'>? <br> A: Arithmetic logic unit <br> B: Register <br> C: Bus <br> D: Control unit",
			answer: "a",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "Which part of the CPU is represented by: <img src='./assets/register.PNG'>? <br> A: Arithmetic logic unit <br> B: Register <br> C: Bus <br> D: Control unit",
			answer: "b",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "Which part of the CPU is represented by: <img src='./assets/cu.PNG'>? <br> A: Arithmetic logic unit <br> B: Register <br> C: Bus <br> D: Control unit",
			answer: "d",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does ALU stand for?",
			answer: "arithmetic logic unit",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does ACC stand for?",
			answer: "accumulator",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does CU stand for?",
			answer: "control unit",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does MAR stand for?",
			answer: "memory address register",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does MDR stand for?",
			answer: "memory data register",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does PC stand for?",
			answer: "program counter",
			answerType: "exact",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "What does RISC stand for?",
			answer: "reduced instruction set computer",
			answerType: "exact",
			topic: "risc and cisc",
		},
		{
			question: "What does CISC stand for?",
			answer: "complex instruction set computer",
			answerType: "exact",
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, uses less power and is cheaper to make?",
			answer: "risc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, runs at a faster clock speed and is larger?",
			answer: "cisc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, is often used in smartphones and tablets?",
			answer: "risc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, has a less complex clock cycle hence is more efficient at performing simpler tasks?",
			answer: "risc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, has a more complex clock cycle hence is more efficient at performing complex tasks?",
			answer: "cisc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which is <strong>not</strong> an <strong>input</strong> device? <br> A: Gyroscope <br> B: Microphone <br> C: Keyboard <br> D: Hard drive",
			answer: "d",
			answerType: "exact",
			topic: "input output",
		},
		{
			question: "Which is <strong>not</strong> an <strong>output</strong> device? <br> A: Monitor <br> B: Gyroscope <br> C: Speaker <br> D: Laser printer",
			answer: "b",
			answerType: "exact",
			topic: "input output",
		},
		{
			question: "What are examples of flash memory? <i>more answers give you more points</i>",
			answer: ["usb","sd","solid-state drive"],
			answerType: "match",
			required: 1,
			topic: "storage devices",
		},
		{
			question: "Which factors must be considered when choosing a suitable secondary storage device? <i>more answers give you more points</i>",
			answer: [["capacity", "size"], "speed", ["portability", "portable"], ["durability", "durable"], ["reliability", "reliable"], ["cost", "price"]],
			answerType: "match",
			required: 1,
			topic: "storage devices",
		},
		{
			question: "How is data transferred between the memory and the CPU?",
			answer: ["bus"],
			answerType: "match",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "What are the <strong>three</strong> types of buses in a CPU?",
			answer: ["control", "address", "data"],
			answerType: "match",
			required: 3,
			topic: "cpu architecture",
		},
		{
			question: "What is the name for 4 bits? <br> A: Chomp <br> B: Byte <br> C: Bit <br> D: Nibble",
			answer: "d",
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "What is the name for 8 bits? <br> A: Chomp <br> B: Chunk <br> C: Byte <br> D: Nibble",
			answer: "c",
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "How many bytes in a kB?",
			answer: ["1000", "1024"],
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "How many kB in a MB?",
			answer: ["1000", "1024"],
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "What does RAM stand for?",
			answer: "random access memory",
			answerType: "exact",
			topic: "RAM ROM",
		},
		{
			question: "What does ROM stand for?",
			answer: "read only memory",
			answerType: "exact",
			topic: "RAM ROM",
		},
		{
			question: "What does GPU stand for?",
			answer: "graphics processing unit",
			answerType: "exact",
			topic: "misc hardware",
		},
		{
			question: "What is the place in the computer where the program and data that are currently in use are stored?",
			answer: "ram",
			answerType: "exact",
			topic: "RAM ROM",
		},
		{
			question: "What is the place in the computer where the programs needed to boot up the computer are stored?",
			answer: "rom",
			answerType: "exact",
			topic: "RAM ROM",
		},
		{
			question: "Does RAM or ROM have a higher memory capacity?",
			answer: "ram",
			answerType: "exact",
			topic: "RAM ROM",
		},
		{
			question: "Which type of computer memory is volatile?",
			answer: "ram",
			answerType: "exact",
			topic: "RAM ROM",
		},
		{
			question: "What type of storage is a hard disk? <br> A: Optical <br> B: Waterman <br> C: Magnetic <br> D: Solid-state",
			answer: "c",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "Which hardware component connects other components together? <i>(HINT: other components are soldered to this)</i>",
			answer: ["motherboard"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "Which hardware component provides output to your speakers? <i>(HINT: uses digital-to-analogue converter)</i>",
			answer: ["sound board"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "What is the abbreviation of the hardware component that performs massive, complex computations on large sets of data? <i>(HINT: primarily used for rendering and displaying graphics to the screen)</i>",
			answer: ["gpu"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "List some common uses of the GPU. <i>more answers give you more points</i>",
			answer: ["gaming", "data", "cryptocurrency", "render"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "List a positive of cloud storage. <i>more answers give you more points</i>",
			answer: ["backup", "access", ["cost", "price"]],
			answerType: "match",
			required: 1,
			topic: "cloud storage",
		},
		{
			question: "List a negative of cloud storage. <i>more answers give you more points</i>",
			answer: ["internet", ["security", "insecure"], ["reliant", "dependent"]],
			answerType: "match",
			required: 1,
			topic: "cloud storage",
		},
		{
			question: "What is the name given to a storage device that is not under the control of the CPU?",
			answer: "secondary storage",
			answerType: "exact",
			topic: "storage devices",
		},
	],
	logic: [
	// also includes evaluation of boolean statements
		{
			question: "What is the hardware's logic controlled by?",
			answer: ["logic gate"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/and.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "a",
			answerType: "exact",
			topic: "logic gate diagrams",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/or.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "b",
			answerType: "exact",
			topic: "logic gate diagrams",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/not.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "c",
			answerType: "exact",
			topic: "logic gate diagrams",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/xor.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "d",
			answerType: "exact",
			topic: "logic gate diagrams",
		},
		{
			question: "Which logic gate has an output of 1 only if all its inputs are 1? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "a",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate has an output of 1 if any of its inputs are 1? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "b",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate has an output of 1 if its input is 0? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "c",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate has an output of 1 if either but not both of its inputs are 1? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "d",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "What does the symbol + mean in logical operations? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "b",
			answerType: "exact",
			topic: "logic gate symbols",
		},
		{
			question: "What does the symbol . mean in logical operations? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "a",
			answerType: "exact",
			topic: "logic gate symbols",
		},
		{
			question: "What does this mean in logical operations? <img src='./assets/notSymbol.PNG'><br> A: AND A <br> B: OR A <br> C: NOT A <br> D: XOR A",
			answer: "c",
			answerType: "exact",
			topic: "logic gate symbols",
		},
		{
			question: "What does this mean in logical operations? <img src='./assets/xorSymbol.PNG'><br> A: A AND B <br> B: A OR B <br> C: A NAND B <br> D: A XOR B",
			answer: "d",
			answerType: "exact",
			topic: "logic gate symbols",
		},
		{
			question: "What law is 'A . 0 = 0'? <br> A: Complement <br> B: Annulment <br> C: Absorptive <br> D: Idempotent",
			answer: "b",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + 1 = 1'? <br> A: Absorptive <br> B: Identity <br> C: Commutative <br> D: Annulment",
			answer: "d",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + 0 = A'? <br> A: Identity <br> B: Idempotent <br> C: Annulment <br> D: Complement",
			answer: "a",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A . 1 = A'? <br> A: Idempotent <br> B: Annulment <br> C: Identity <br> D: Commutative",
			answer: "c",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + A = A'? <br> A: Idempotent <br> B: Distributive <br> C: Associative <br> D: Absorptive",
			answer: "a",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A . A = A'? <br> A: Complement <br> B: Double Complement <br> C: Distributive <br> D: Idempotent",
			answer: "d",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A . Ā = 0'? <br> A: Double Complement <br> B: Annulment <br> C: Commutative <br> D: Complement",
			answer: "d",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + Ā = 1'? <br> A: Idempotent <br> B: Complement <br> C: Double Complement <br> D: Identity",
			answer: "b",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A.B = B.A'? <br> A: Associative <br> B: Complement <br> C: Commutative <br> D: Distributive",
			answer: "c",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + B = B + A'? <br> A: Commutative <br> B: Annulment <br> C: Complement <br> D: Double Complement",
			answer: "a",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'NOT NOT A = A'? <br> A: Annulment <br> B: Complement <br> C: Double Complement <br> D: Identity",
			answer: "c",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A(B + C) = A.B + A.C'? <br> A: Commutative <br> B: Distributive <br> C: Double Complement <br> D: Associative",
			answer: "b",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + (B.C) = (A + B).(A + C)'? <br> A: Distributive <br> B: Identity <br> C: Complement <br> D: Commutative",
			answer: "a",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + (A.B) = A'? <br> A: Complement <br> B: Associative <br> C: Identity <br> D: Absorptive",
			answer: "d",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A(A + B) = A'? <br> A: Idempotent <br> B: Complement <br> C: Absorptive <br> D: De Morgan's",
			answer: "c",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A + (B + C) = (A + B) + C = A + B + C'? <br> A: Associative <br> B: Distributive <br> C: De Morgan's <br> D: Complement",
			answer: "a",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'A(B.C) = (A.B)C = A.B.C'? <br> A: De Morgan's <br> B: Associative <br> C: Distributive <br> D: Absorptive",
			answer: "b",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
		{
			question: "What law is 'NOT(A+B) = NOT A . NOT B'? <br> A: Distributive <br> B: Double Complement <br> C: De Morgan's <br> D: Associative",
			answer: "c",
			answerType: "exact",
			topic: "boolean algebra laws",
		},
	],
	communication: [
		{
			question: "What is the name given to a collection of computers that are connected together?",
			answer: "network",
			answerType: "exact",
			topic: "networks",
		},
		{
			question: "What is the name given to a computer that is not connected to a network?",
			answer: [["stand-alone", "stand alone"]],
			answerType: "match",
			required: 1,
			topic: "networks",
		},
		{
			question: "List an advantage of a network. <i>more answers give you more points</i>",
			answer: ["share", "access", "control", "security", "backup", ["communication", "communicate"], "connect"],
			answerType: "match",
			required: 1,
			topic: "networks",
		},
		{
			question: "List a disadvantage of a network. <i>more answers give you more points</i>",
			answer: ["security", "malware", "control", "dependent", "traffic", ["speed", "slow"]],
			answerType: "match",
			required: 1,
			topic: "networks",
		},
		{
			question: "What does LAN stand for?",
			answer: "local area network",
			answerType: "exact",
			topic: "network types",
		},
		{
			question: "What does WAN stand for?",
			answer: "wide area network",
			answerType: "exact",
			topic: "network types",
		},
		{
			question: "What does PAN stand for?",
			answer: "personal area network",
			answerType: "exact",
			topic: "network types",
		},
		{
			question: "What type of network can be difficult to manage the security of?",
			answer: [["wan", "wide area"]],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "What type of network has the greatest chance of error?",
			answer: [["wan", "wide area"]],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "List a common type of PAN. <i>more answers give you more points</i>",
			answer: ["bluetooth", "usb"],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "What type of network covers a small geographical area (such as a building or small site of buildings)?",
			answer: [["lan", "local area"]],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "What type of network covers a large geographical area (such as a city, country, or even several countries)?",
			answer: [["wan", "wide area"]],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/star.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "a",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/ring.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "b",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/bus.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "c",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/mesh.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "d",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "What is the result of two devices on the same network attempting to transmit data at the same time down the same connection?",
			answer: ["data collision"],
			answerType: "match",
			required: 1,
			topic: "network topology",
		},
		{
			question: "What is the name given to the physical structure of a network?",
			answer: ["topology"],
			answerType: "match",
			required: 1,
			topic: "network topology",
		},
		{
			question: "I want a network topology that is cheap and easy to expand. <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "c",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "I want a network topology that is easy to monitor, audit, and find faults. <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "a",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "I want a network topology with excellent performance. <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "d",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which network topology is most expensive? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "d",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which network topology is impossible to expand without bringing the rest of the network down? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "b",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which network topology is reliant on a 'central node' (hence if it goes down the whole network goes down)? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "a",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "List a method to connect devices in a wired network. <i>more answers give you more points</i>",
			answer: ["coaxial", "twisted pair", ["fibre optic", "fibre-optic"], "copper wire"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "Which type of transmission media is fastest but also most expensive?",
			answer: [["fibre optic", "fibre-optic"]],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "Which type of transmission media is most commonly used in ethernet?",
			answer: ["twisted pair"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "What is the main cause of errors in wired networks?",
			answer: ["interference", "packet loss"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "What is the name for a digit that can be used to verify that there have been no errors in data transmission?",
			answer: ["checksum"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "What does NIC stand for?",
			answer: ["network interface controller", "network interface card"],
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What is the abbreviation for the piece of hardware installed into a computer to allow it to be connected to a wired network?",
			answer: "nic",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What is the name given to the unique identifier assigned to the NIC?",
			answer: "mac address",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What does WNIC stand for?",
			answer: "wireless network interface controller",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What is the abbreviation for the piece of hardware installed into a computer to allow it to be connected to a wireless network?",
			answer: "wnic",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "Which type of network (wired or wireless) is generally faster?",
			answer: ["wired"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "wired and wireless",
		},
		{
			question: "Which type of network (wired or wireless) is generally less secure (easier to intercept)?",
			answer: ["wireless"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "wired and wireless",
		},
		{
			question: "What is a 'set of rules that govern network operations' known as?",
			answer: "protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "List the abbreviation of a common protocol or protocol family. <i>more answers give you more points</i>",
			answer: ["tcp", "ip", "http", "https", "ftp", "pop", "imap", "smtp", ["wi-fi", "wifi"], "ethernet"],
			answerType: "match",
			required: 1,
			topic: "protocols",
		},
		{
			question: "What does TCP stand for?",
			answer: "transmission control protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does HTTP stand for?",
			answer: "hypertext transfer protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does HTTPS stand for?",
			answer: "hypertext transfer protocol secure",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does FTP stand for?",
			answer: "file transfer protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does POP stand for?",
			answer: "post office protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does IMAP stand for?",
			answer: "internet message access protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does SMTP stand for?",
			answer: "simple mail transfer protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which <strong>three</strong> protocols (their abbreviations) are used to transmit files across a network?",
			answer: ["tcp", "ip", "ftp"],
			answerType: "match",
			required: 3,
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used by web browsers to access websites by communicating with a web server</li><li>Does not encrypt and decrypt data sent/received</li></ul>",
			answer: "http",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used by web browsers to access websites by communicating with a web server</li><li>Encrypts and decrypts data sent/received</li></ul>",
			answer: "https",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used to retrieve emails from a server</li><li>Deletes the emails from the server once they have been downloaded</li></ul>",
			answer: "pop",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used to retrieve emails from a server</li><li>Does not delete the emails from the server until the user deletes them</li></ul>",
			answer: "imap",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Governs the sending of emails using a network</li></ul>",
			answer: "smtp",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which family of protocols standardise wireless communications?",
			answer: "wi-fi",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which family of protocols standardise wired communications?",
			answer: "ethernet",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with collecting and distributing data</li><li>Makes sure data is in a suitable format for transmission</li></ul>",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with establishing and terminating connections between devices on a network (through the use of a router)</li><li>Performs error detection and correction functions</li></ul>",
			answer: ["transport"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with establishing and terminating the route to the destination of the data packet</li></ul>",
			answer: ["network"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with the transmission media that is used to send data over a local network</li><li>Converts the data to an appropriate format for the transmission media</li></ul>",
			answer: ["physical"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Drives the physical transmission of electrical signals across the network</li></ul>",
			answer: ["data link"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer is where programs that use the network are operated?",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer is most abstract?",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "What are the three elements of a packet?",
			answer: ["header", "payload", "trailer"],
			answerType: "match",
			required: 3,
			topic: "switching",
		},
		{
			question: "Which of 'packet switching' or 'circuit switching' ensures the data packets arrive in order at the location?",
			answer: ["circuit"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "Which of 'packet switching' or 'circuit switching' allows multiple packets to be sent over the network at the same time?",
			answer: ["packet"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "Which of 'packet switching' or 'circuit switching' still works if a computer on the network fails?",
			answer: ["packet"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "Which of 'packet switching' or 'circuit switching' is used for a landline phone system?",
			answer: ["circuit"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "Which of 'packet switching' or 'circuit switching' establishes a dedicated link between the start and end node?",
			answer: ["circuit"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "What are the two types of routing?",
			answer: ["dynamic", "static"],
			answerType: "match",
			required: 2,
			topic: "routing",
		},
		{
			question: "Which of 'dynamic routing' or 'static routing' allows congested parts of the network to be avoided?",
			answer: ["dynamic"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "routing",
		},
		{
			question: "Which of 'dynamic routing' or 'static routing' is more straightforward to implement?",
			answer: ["static"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "routing",
		},
		{
			question: "Which of 'dynamic routing' or 'static routing' involves data packets taking different routes rather than following a pre-set path?",
			answer: ["dynamic"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "routing",
		},
		{
			question: "What stores the routing cost for each route (as laid out by the network administrator) and is used to determine the route that should be taken by data packets?",
			answer: "routing table",
			answerType: "exact",
			topic: "routing",
		},
		{
			question: "Which type of network is the Internet an example of? <br> A: LAN <br> B: WAN <br> C: PAN <br> D: CAN",
			answer: "b",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is the name given to the collection of web pages we access using the Internet?",
			answer: "world wide web",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is assigned to a device every time it connects to the internet (given to devices using the Internet Protocol)?",
			answer: "ip address",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "Where are IP addresses stored?",
			answer: ["server"],
			answerType: "match",
			required: 1,
			topic: "internet",
		},
		{
			question: "What does DNS stand for?",
			answer: "domain name system",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is the name given to a collection of web pages that we may want to view?",
			answer: ["domain"],
			answerType: "match",
			required: 1,
			topic: "internet",
		},
		{
			question: "What keeps a directory of all the domain names along with their IP addresses?",
			answer: "dns",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is the system that means we do not need to remember the IP address to a website (only the domain name)?",
			answer: "dns",
			answerType: "exact",
			topic: "internet",
		},
	],
	data: [
		// also includes hex, binary, denary conversion, addition of binary, binary shift
		{
			question: "What error is given when the total from adding binary numbers cannot be stored within a byte of data? <br> A: Logical error <br> B: Overflow error <br> C: Stack error <br> D: Binary error",
			answer: "b",
			answerType: "exact",
			topic: "errors",
		},
		{
			question: "What mathematical operation does a left arithmetic shift apply? <br> A: Addition <br> B: Subtraction <br> C: Multiplication <br> D: Division",
			answer: "c",
			answerType: "exact",
			topic: "binary shift",
			suddenDeath: true,
		},
		{
			question: "What mathematical operation does a left arithmetic shift apply? <br> A: Addition <br> B: Subtraction <br> C: Multiplication <br> D: Division",
			answer: "d",
			answerType: "exact",
			topic: "binary shift",
			suddenDeath: true,
		},
		{
			question: "What information does metadata store for <strong>graphics files</strong>? <i>more answers give you more points</i>",
			answer: ["dimension", "resolution", "compression", "depth", "colour", "author", "time", "date", "creator", "purpose", "size", "source", "quality", "location"],
			answerType: "match",
			required: 1,
			topic: "metadata",
		},
		{
			question: "What information does metadata store for <strong>sound files</strong>? <i>more answers give you more points</i>",
			answer: ["resolution", "compression", ["sample rate", "sampling rate", "sample frequency", "sampling frequency"], "author", "length", "time", "date", "creator", "purpose", "size", "source", "quality", "location"],
			answerType: "match",
			required: 1,
			topic: "metadata",
		},
		{
			question: "What can be described as 'data about data'?",
			answer: "metadata",
			answerType: "exact",
			topic: "metadata",
		},
		{
			question: "List an example of a character set. <i>more answers give you more points</i>",
			answer: ["ascii", "unicode", "iso"],
			answerType: "match",
			required: 1,
			topic: "character sets",
		},
		{
			question: "What is the name of the character set that is a subset of unicode, and contains 128 codes?",
			answer: "ascii",
			answerType: "exact",
			topic: "character sets",
		},
		{
			question: "What is the name of the character set that is a superset of ascii, and contains up to 2^21 codes?",
			answer: "unicode",
			answerType: "exact",
			topic: "character sets",
		},
		{
			question: "What is the measurement of sampling rate?",
			answer: ["hertz", "hz"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Which <strong>three</strong> factors affect file size of a sound file?",
			answer: ["length", ["sample rate", "sampling rate", "sample frequency", "sampling frequency"], "resolution"],
			answerType: "match",
			required: 3,
			topic: "sound files",
		},
		{
			question: "Which factors can affect quality of a sound file's playback? <i>more answers give you more points</i>",
			answer: [["sample rate", "sampling rate", "sample frequency", "sampling frequency"], "resolution"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Find the file size of a sound file that is 10 seconds long, has a 150Hz sample rate, and has an 8 bit sample resolution. Give your answer in bytes.",
			answer: "1500",
			answerType: "exact",
			topic: "sound files",
		},
		{
			question: "Find the file size of a sound file that is 10 seconds long, has a 100Hz sample rate, and has an 4 bit sample resolution. Give your answer in bits.",
			answer: "4000",
			answerType: "exact",
			topic: "sound files",
		},
		{
			question: "Which <strong>two</strong> factors affect file size of a graphics file?",
			answer: [["dimensions", "size"], "colour depth"],
			answerType: "match",
			required: 2,
			topic: "graphics files",
		},
		{
			question: "What is the colour depth of an image with 256 possible colours?",
			answer: 8,
			answerType: "exact",
			topic: "graphics files",
		},
		{
			question: "Find the file size of a graphics file that is 100 pixels by 100 pixels, and has a colour depth of 16. Give your answer in bytes.",
			answer: "20000",
			answerType: "exact",
			topic: "graphics files",
		},
		{
			question: "Find the file size of a graphics file that is 400 pixels by 800 pixels, and has a colour depth of 2. Give your answer in kilobytes.",
			answer: "80",
			answerType: "exact",
			topic: "graphics files",
		},
		{
			question: "What data type is '3.4'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '2.0'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '2'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "a",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is 'true'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "c",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is 'V'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "d",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '@'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "d",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is 'Computer science is fun!'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "e",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is ['Bob', 'Jane', 'Bill']? <br> A: String <br> B: One-dimensional string array <br> C: Two-dimensional string array <br> D: Three-dimensional string array",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '@'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "d",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What is the name of an array that does not have a fixed length?",
			answer: ["dynamic"],
			answerType: "match",
			required: 1,
			topic: "data types",
		},
		{
			question: "What is the name of an array that has a fixed length?",
			answer: ["static"],
			answerType: "match",
			required: 1,
			topic: "data types",
		},
		{
			question: "Which is an array of different data types? <br> A: Table <br> B: Record <br> C: Field <br> D: Database",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "Which is an array of the same data type? <br> A: Table <br> B: Record <br> C: Field <br> D: Database",
			answer: "c",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What is the name of the process that checks to ensure that data entered is reasonable and sensible?",
			answer: "validation",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "List a common validation rule that can be used. <i>more answers give you more points</i>",
			answer: ["length", "range", "type", "format", "presence", "list"],
			answerType: "match",
			required: 1,
			topic: "validation",
		},
		{
			question: "Which validation rule checks that the data entered contains a set number of characters? <br> A: Length check <br> B: Range check <br> C: Type check <br> D: Format check <br> E: Presence check",
			answer: "a",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "Which validation rule checks that the data is of a certain data type? <br> A: Length check <br> B: Range check <br> C: Type check <br> D: Format check <br> E: Presence check",
			answer: "c",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "Which validation rule checks that data has been entered into the input box? <br> A: Length check <br> B: Range check <br> C: Type check <br> D: Format check <br> E: Presence check",
			answer: "e",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "What is the name of the process that checks data entered into the system matches data from the source document?",
			answer: "verification",
			answerType: "exact",
			topic: "verification",
		},
		{
			question: "List a common verification method that can be used. <i>more answers give you more points</i>",
			answer: ["double keying", "proofreading"],
			answerType: "match",
			required: 1,
			topic: "verification",
		},
	],
	software: [
		{
			question: "Which type of software controls the operation of hardware in a computer?",
			answer: ["system"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of software is the everyday programs that we use to create documents and perform tasks?",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of software provides a platform to run applications software?",
			answer: ["system"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "List a type of system software. <i>more answers give you more points</i>",
			answer: ["device driver", "utility software", ["operating system", "os"]],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of system software: <ul><li>Is loaded by the computer after the initial boot-up</li><li>Controls the operations of the hardware</li><li>Manages all other software</li></ul>",
			answer: [["operating system", "os"]],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of system software is designed to help to analyze, configure, optimize or maintain a computer?",
			answer: "utility",
			answerType: "exact",
			topic: "misc software",
		},
		{
			question: "Which type of system software: <ul><li>Controls a particular device connected to a computer system</li><li>Is controlled by the operating system</li></ul>",
			answer: "device driver",
			answerType: "exact",
			topic: "misc software",
		},
		{
			question: "Give a role of the operating system. <i>more answers give you more points</i>",
			answer: ["interface", "memory", "multitask", "peripheral", "driver", "user", "file", "processes", "resource", ["secondary storage", "backing store", "backing storage"]],
			answerType: "match",
			required: 1,
			topic: "operating system",
		},
		{
			question: "What are the <strong>two</strong> main roles of the operating system?",
			answer: ["interface", "resource"],
			answerType: "match",
			required: 2,
			topic: "operating system",
		},
		{
			question: "What does GUI stand for?",
			answer: "graphical user interface",
			answerType: "exact",
			topic: "interfaces",
		},
		{
			question: "What does CLI stand for?",
			answer: "command line interface",
			answerType: "exact",
			topic: "interfaces",
		},
		{
			question: "What does NLI stand for?",
			answer: "natural language interface",
			answerType: "exact",
			topic: "interfaces",
		},
		{
			question: "Give a common example of an NLI. <i>more answers give you more points</i>",
			answer: ["siri", "alexa", "cortana", "google assistant"],
			answerType: "match",
			required: 1,
			topic: "interfaces",
		},
		{
			question: "Give a common example of a peripheral. <i>more answers give you more points</i>",
			answer: ["mouse", "keyboard", "microphone", "printer", "scanner", "monitor", "touchscreen", "camera"],
			answerType: "match",
			required: 1,
			topic: "peripherals",
		},
		{
			question: "Which is NOT a peripheral? <br> A: Mouse <br> B: Printer <br> C: Hard drive <br> D: USB stick",
			answer: "c",
			answerType: "exact",
			topic: "peripherals",
		},
		{
			question: "Give a task that utility software may be responsible for. <i>more answers give you more points</i>",
			answer: ["file conversion", "file repair", "compression", "backup", "encryption", "defragmentation", ["antivirus", "anti-virus", "anti-malware", "antimalware"]],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Give <strong>two</strong> types of utility software that can speed up the run speed of a computer.",
			answer: ["compression", "defragmentation", ["antivirus", "anti-virus", "anti-malware", "antimalware"]],
			answerType: "match",
			required: 2,
			topic: "misc software",
		},
		{
			question: "Which is the sequence of bits used to encrypt or decrypt data? <br> A: Encryption key <br> B: Encryption algorithm <br> C: Plain text <br> D: Cypher text",
			answer: "a",
			answerType: "exact",
			topic: "encryption",
		},
		{
			question: "List a common type of encryption algorithm. <i>more answers give you more points</i>",
			answer: ["xor", "caesar cipher"],
			answerType: "match",
			required: 1,
			topic: "encryption",
		},
		{
			question: "Which type of encryption uses the same encryption key to encrypt and decrypt the data?",
			answer: ["symmetric"],
			answerType: "match",
			required: 1,
			topic: "encryption",
		},
		{
			question: "Which type of encryption uses a different encryption key to encrypt and decrypt the data?",
			answer: ["asymmetric"],
			answerType: "match",
			required: 1,
			topic: "encryption",
		},
		{
			question: "Which stage of the encryption/decryption process is a <strong>private key</strong> used for in asymmetric encryption?",
			answer: ["decrypt"],
			answerType: "match",
			required: 1,
			topic: "encryption",
		},
		{
			question: "Which type of backup only backs up files that have changed since the last backup was carried out?",
			answer: ["incremental"],
			answerType: "match",
			required: 1,
			topic: "backup",
		},
	],
	// topics that are small enough to not be worth their own section
	misc: [
		// principles of programming
		{
			question: "List a high-level language. <i>more answers give you more points</i>",
			answer: ["python", "javascript", "java", "c#", "c++", "go", "lisp", "scala", "ruby", "cobol", "pascal", "basic", "matlab"],
			answerType: "match",
			required: 1,
			topic: "programming languages",
		},
		{
			question: "List a low-level language. <i>more answers give you more points</i>",
			answer: ["assembly", "machine"],
			answerType: "match",
			required: 1,
			topic: "programming languages",
		},
		{
			question: "List a benefit of high-level languages. <i>more answers give you more points</i>",
			answer: ["read", "productivity", "learn", "maintain", "understand", "write"],
			answerType: "match",
			required: 1,
			topic: "programming languages",
		},
		{
			question: "List a benefit of low-level languages. <i>more answers give you more points</i>",
			answer: [["speed", "fast"], "control"],
			answerType: "match",
			required: 1,
			topic: "programming languages",
		},
		// software engineering
		{
			question: "What does IDE stand for?",
			answer: "integrated development environment",
			answerType: "exact",
			topic: "IDEs",
		},
		{
			question: "List a feature of an IDE. <i>more answers give you more points</i>",
			answer: ["code editor", "runtime environment", "error diagnostic"],
			answerType: "match",
			required: 1,
			topic: "IDEs",
		},
		{
			question: "List a way to debug a program using an IDE. <i>more answers give you more points</i>",
			answer: ["trace", ["break point", "breakpoint"], "memory inspection", "variable watch"],
			answerType: "match",
			required: 1,
			topic: "error debugging",
		},
		{
			question: "Which error diagnostic facility displays the order in which the lines of a program are executed, and possibly the values of variables as the program is being run?",
			answer: "trace",
			answerType: "exact",
			topic: "error debugging",
		},
		{
			question: "Which error diagnostic facility interrupts a program on a specific line of code, allowing the programmer to compare the values of variables against expected values? The program code can then usually be executed one line at a time.",
			answer: "break point",
			answerType: "exact",
			topic: "error debugging",
		},
		{
			question: "Which error diagnostic facility displays the current value of any variable as the program code is single-stepped?",
			answer: "variable watch",
			answerType: "exact",
			topic: "error debugging",
		},
		{
			question: "Which error diagnostic facility displays the contents of a section of memory?",
			answer: "memory inspection",
			answerType: "exact",
			topic: "error debugging",
		},
		// program construction
		{
			question: "List a type of translator. <i>more answers give you more points</i>",
			answer: ["compiler", "interpreter", "assembler"],
			answerType: "match",
			required: 1,
			topic: "translators",
		},
		{
			question: "Which type of translator translates one line at a time?",
			answer: "interpreter",
			answerType: "exact",
			suddenDeath: true,
			topic: "translators",
		},
		{
			question: "Which type of translator translates all lines at once?",
			answer: "compiler",
			answerType: "exact",
			suddenDeath: true,
			topic: "translators",
		},
		{
			question: "Which type of translator translates assembly language?",
			answer: "assembler",
			answerType: "exact",
			suddenDeath: true,
			topic: "translators",
		},
		{
			question: "Which type of translator produces an executable file which runs the program?",
			answer: "compiler",
			answerType: "exact",
			suddenDeath: true,
			topic: "translators",
		},
		{
			question: "Which type of translator gives a log of all errors (rather than stopping at the first error)?",
			answer: "compiler",
			answerType: "exact",
			suddenDeath: true,
			topic: "translators",
		},
		{
			question: "Which type of translator stops translation at the first error reached?",
			answer: "interpreter",
			answerType: "exact",
			suddenDeath: true,
			topic: "translators",
		},
		{
			question: "Which type of translator does <strong>not</strong> create a stand-alone file?",
			answer: "interpreter",
			answerType: "exact",
			suddenDeath: true,
			topic: "translators",
		},
		{
			question: "List a positive of compilation. <i>more answers give you more points</i>",
			answer: ["distribution", "execution speed", "optimisation", "dependencies", "size", "debug"],
			answerType: "match",
			required: 1,
			topic: "translators",
		},
		{
			question: "List a positive of interpretation. <i>more answers give you more points</i>",
			answer: ["easier to implement", "no compilation", "debug"],
			answerType: "match",
			required: 1,
			topic: "translators",
		},
		{
			question: "List a stage involved in the compilation process. <i>more answers give you more points</i>",
			answer: ["lexical analysis", "symbol table construction", "syntax analysis", "semantic analysis", "linking", "loading", "code generation", "optimisation"],
			answerType: "match",
			required: 1,
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves removing white space?",
			answer: "lexical analysis",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves storing variable and subroutine names?",
			answer: "symbol table construction",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves checking the syntax is correct?",
			answer: "syntax analysis",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves checking variable types?",
			answer: "semantic analysis",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves checking links to previously compiled code (e.g. libraries) exist, and linking them in?",
			answer: "linking",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves loading previously compiled code (e.g. libraries) into memory?",
			answer: "loading",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves converting the code into object code (understood by computer)?",
			answer: "code generation",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves making the program run better on the processor?",
			answer: "optimisation",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which <strong>two</strong> factors does the optimisation process (for code compilation) improve about the code?",
			answer: ["speed", "size"],
			answerType: "match",
			required: 1,
			topic: "compilation process",
		},
		{
			question: "List a type of error that can occur during programming. <i>more answers give you more points</i>",
			answer: ["syntax", "logic", "runtime", "linking", "rounding", "truncation"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is caused by division by 0?",
			answer: ["runtime"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is caused by division by incorrect parameters for a subroutine?",
			answer: ["runtime"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is thrown before the program runs?",
			answer: ["syntax"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is caused by a library not being able to be found?",
			answer: ["linking"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is caused by number rounding making a variable inaccurate?",
			answer: ["rounding"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
	],
	security: [
		{
			question: "What are the <strong>two</strong> categories of danger that exist when storing personal data on computers?",
			answer: ["accidental", "malicious"],
			answerType: "match",
			required: 2,
			topic: "data protection",
		},
		{
			question: "How can personal data be protected? <i>more answers give you more points</i>",
			answer: ["hash", "password", "access level", "encryption", ["two factor authentication", "two-factor authentication"]],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "What is the name given to the process that reduces a file's size for efficient storage and transmission?",
			answer: "compression",
			answerType: "exact",
			topic: "compression",
		},
		{
			question: "What is a positive of a lossless file format?",
			answer: ["quality", ["no data lost", "don't lose data"]],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "What is a negative of a lossless file format?",
			answer: ["size"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Give a common example of a lossless sound file format. <i>more answers give you more points</i>",
			answer: ["wav", "aiff", "flac", "alac", "ape"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Give a common example of a lossy sound file format. <i>more answers give you more points</i>",
			answer: ["mp3", "aac", "vorbis", "wma"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Which best describes 'malware'? <br> A: A program that speeds up a computer's processing speed <br> B: Illegally downloaded media <br> C: A program designed to do harm to a computer or its data <br> D: A program that is downloaded from an email attachment ",
			answer: "c",
			answerType: "exact",
			topic: "malware",
		},
		{
			question: "List a common example of malware. <i>more answers give you more points</i>",
			answer: ["virus", "worm", "trojan", ["keylogger", "key logger"], "adware", "spyware", "randomware"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "List a common example of spyware. <i>more answers give you more points</i>",
			answer: [["keylogger", "key logger"], "adware"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Infiltrates a computer system and replicates itself</li><li>Requires human involvement to duplicate</li><li>Causes damage by corrupting data or using up all available memory</li></ul>",
			answer: ["virus"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Infiltrates a computer system and replicates itself</li><li>Does not require human involvement to duplicate</li><li>Causes damage by corrupting data or usingup all available memory</li></ul>",
			answer: ["worm"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Is disguised as a harmless file or download</li></ul>",
			answer: ["trojan"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Records keypresses from a user on a computer</li><li>Can pick out personal and sensitive data (such as passwords)</li></ul>",
			answer: [["keylogger", "key logger"]],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Injects adverts into pages and programs on a computer</li><li>May come with other types of malware</li></ul>",
			answer: ["adware"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "List a method of protection against malware. <i>more answers give you more points</i>",
			answer: [["antivirus", "anti-virus", "anti-malware", "antimalware"], "update", "web filter", "firewall"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "List a way companies can protect themselves against malware and its impacts. <i>more answers give you more points</i>",
			answer: ["acceptable use policy", "disaster recovery policy", ["antivirus", "anti-virus", "anti-malware", "antimalware"], "penetration testing", "footprinting", ["bounties", "bounty"], ["ethical hacking", "white-hat", "white hat"], "firewall", "web filter", "update"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which type of policy stipulates what users of a network may and may not do with that network?",
			answer: ["acceptable use"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which type of policy describes how a company would aim to recover from catastrophic damage to hardware, software, or data?",
			answer: ["disaster recovery"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which factors make a password more secure? <i>more answers give you more points</i>",
			answer: ["length", "character", "symbol", "uppercase", ["alphanumeric", "number"]],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "What is the name given to storing data that is no longer in current or frequent use?",
			answer: ["archiving"],
			answerType: "match",
			required: 1,
			topic: "archiving",
		},
		{
			question: "Why might data be archived and not deleted? <i>more answers give you more points</i>",
			answer: ["security", ["legal", "law"], ["historical", "history"]],
			answerType: "match",
			required: 1,
			topic: "archiving",
		},
		{
			question: "List a form of cyberattack. <i>more answers give you more points</i>",
			answer: [["shoulder surfing", "shoulder-surfing"], "sql injection", "dos attack", "ddos attack", ["ip address spoofing", "ip spoofing"], "password", "buffer overflow attack"],
			answerType: "match",
			required: 1,
			topic: "cyberattack",
		},
		{
			question: "List a type of password-based attack. <i>more answers give you more points</i>",
			answer: ["dictionary", "brute force", "guess"],
			answerType: "match",
			required: 1,
			topic: "cyberattack",
		},
		{
			question: "List a way companies can protect themselves against cyberattack. <i>more answers give you more points</i>",
			answer: ["validation", ["scripting restriction", "script restriction"], "penetration testing", "footprinting", ["bounties", "bounty"], ["ethical hacking", "white-hat", "white hat"], "update"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which best describes 'social engineering'? <br> A: Designing and building areas for socialisation <br> B: Convincing people not to download malware <br> C: Engineering with friends <br> D: Tricking people into breaking security procedures ",
			answer: "d",
			answerType: "exact",
			topic: "social engineering",
		},
		{
			question: "List a common example of social engineering. <i>more answers give you more points</i>",
			answer: ["blagging", "phishing", "fraud", "pharming"],
			answerType: "match",
			required: 1,
			topic: "social engineering",
		},
		{
			question: "Which type of social engineering involves: <ul><li>Convincing someone you are someone else</li><li>Tricking them to directly give away information such as passwords</li></ul>",
			answer: ["blagging"],
			answerType: "match",
			required: 1,
			topic: "social engineering",
		},
		{
			question: "Which type of social engineering involves: <ul><li>Sending emails pretending to be a reputable company</li><li>Trying to gain personal details or install malware through this email</li></ul>",
			answer: ["phishing"],
			answerType: "match",
			required: 1,
			topic: "social engineering",
		},
		{
			question: "List a way companies can diagnose security vulnerabilites with their system. <i>more answers give you more points</i>",
			answer: ["penetration testing", "footprinting", ["bounties", "bounty"], ["white-hat", "white hat"], "ethical hacking"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which process: <ul><li>Involves employing a team of people to simulate potential attacks on their network</li><li>Reveals security weak points for a company</li></ul>",
			answer: ["penetration testing"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which process: <ul><li>Involves gathering all available information about the computer system or network and the devices that are attached to it/li><li>Allows an orgnaisation to limit publicly available information about their system</li></ul>",
			answer: ["footprinting"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "List a role of Internet cookies. <i>more answers give you more points</i>",
			answer: ["preference", "advert", "login", "information", "remember"],
			answerType: "match",
			required: 1,
			topic: "cookies",
		},
	],
	impacts: [
		{
			question: "Which best describes 'ethics'? <br> A: How something works <br> B: A set of moral principles <br> C: What governments think about an issue <br> D: A fill-up for a GCSE spec ",
			answer: "b",
			answerType: "exact",
			topic: "ethical impacts",
		},
		{
			question: "List an ethical impact of technology. <i>more answers give you more points</i>",
			answer: ["privacy", ["cybersecurity", "security"], ["hacking", "hacker"], "access", "equality"],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "List a possible cause of loss of privacy due to technology. <i>more answers give you more points</i>",
			answer: ["monitoring", "interception", "distribution", "theft", "hacking"],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "List a type of hacker. <i>more answers give you more points</i>",
			answer: [["white-hat", "white hat"], ["black-hat", "black hat"], ["grey-hat", "grey hat"]],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "Which type of hacker is seen as most ethical?",
			answer: [["white-hat", "white hat", "white-hat hacker", "white hat hacker"]],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "Which best describes 'legislation'? <br> A: A penalty that applies to someone who breaks the law <br> B: The altering of existing law(s) by a government <br> C: Law(s) introduced by a government <br> D: Protest against a law ",
			answer: "c",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which best describes 'sanction'? <br> A: A penalty that applies to someone who breaks the law <br> B: The altering of existing law(s) by a government <br> C: Law(s) introduced by a government <br> D: Protest against a law ",
			answer: "a",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "List a type of sanction. <i>more answers give you more points</i>",
			answer: ["fine", "prison"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Limits the amount of data that an organisation is allowed to collect about a person</li><li>Governs the security of the data when it has been collected</li></ul>",
			answer: ["data protection"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "What year was the Data Protection Act passed?",
			answer: "1998",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Protects personal data held by organisations from hackers</li></ul>",
			answer: ["computer misuse"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "What year was the Computer Misuse Act passed?",
			answer: "1990",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Protects intellectual property</li></ul>",
			answer: ["copyright", "design", "patents"],
			answerType: "match",
			required: 3,
			topic: "legislation",
		},
		{
			question: "What year was the Copyright, Designs and Patents Act passed?",
			answer: "1988",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "What crime does the Copyright, Designs and Patents Act combat?",
			answer: "piracy",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Makes it possible for the public to access information about a public organisation</li><li>Requires public organisations to publish certain data on a regular basis</li></ul>",
			answer: ["freedom of information"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "What year was the Freedom of Information Act passed?",
			answer: "2000",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "List an example of a type of public organisation (according to the Freedom of Information Act). <i>more answers give you more points</i>",
			answer: ["school", "university", "parliament", "council", "police", "government", "nhs", "army"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "Which of these does not apply to a Creative Commons license? <br> A: There are many different types of the license <br> B: Work may be shared freely if under this license <br> C: Licenses provided by Creative Commons organisation <br> D: Individual must ask owner's position to use work under this license ",
			answer: "d",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "List a type of Creative Commons license. <i>more answers give you more points</i>",
			answer: ["attribution", "share-alike", "non-commerical", "no derivative works"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "List a negative impact of technology on the environment. <i>more answers give you more points</i>",
			answer: ["waste", "pollution", "resource", "landfill", "material", "packaging", "energy"],
			answerType: "match",
			required: 1,
			topic: "environmental impacts",
		},
		{
			question: "List a positive impact of technology on the environment. <i>more answers give you more points</i>",
			answer: ["education", "communication", "research", "transport"],
			answerType: "match",
			required: 1,
			topic: "environmental impacts",
		},
		{
			question: "Which typically uses the least power? <br> A: Large monitor desktop computer <br> B: Small monitor desktop computer <br> C: Large monitor laptop computer <br> D: Small monitor laptop computer ",
			answer: "d",
			answerType: "exact",
			topic: "environmental impacts",
		},
	],
	misc2: [
		// component 2
		{
			question: "What is the name given to breaking a large problem down into a series of sub problems?",
			answer: "decomposition",
			answerType: "exact",
			topic: "problem solving",
		},
		{
			question: "What is the name given to reducing something to the simplest set of characteristics that are most relevant to solving the problem?",
			answer: "abstraction",
			answerType: "exact",
			topic: "problem solving",
		},
		{
			question: "List a type of sub routine. <i>more answers give you more points</i>",
			answer: ["procedure", "function", "method"],
			answerType: "match",
			required: 1,
			topic: "sub routines",
		},
		{
			question: "Which type of sub routine does not return a value?",
			answer: "procedure",
			answerType: "exact",
			topic: "sub routines",
		},
		{
			question: "Which type of sub routine returns a value?",
			answer: "function",
			answerType: "exact",
			topic: "sub routines",
		},
		{
			question: "List a positive of using sub routines. <i>more answers give you more points</i>",
			answer: ["decompose", "reuse", ["readable", "readability"], "duplicate"],
			answerType: "match",
			required: 1,
			topic: "sub routines",
		},
		{
			question: "What are the <strong>three</strong> basic constructs used to design algorithms?",
			answer: ["sequence", "selection", "iteration"],
			answerType: "match",
			required: 3,
			topic: "sequence selection iteration",
		},
		{
			question: "Which programming construct involves instructions being given in a particular order?",
			answer: "sequence",
			answerType: "exact",
			topic: "sequence selection iteration",
		},
		{
			question: "Which programming construct involves a decision being made?",
			answer: "selection",
			answerType: "exact",
			topic: "sequence selection iteration",
		},
		{
			question: "Which programming construct involves a set of steps being carried out more than once or many times?",
			answer: "iteration",
			answerType: "exact",
			topic: "sequence selection iteration",
		},
		{
			question: "Which programming construct involves a set of steps being carried out more than once or many times?",
			answer: "iteration",
			answerType: "exact",
			topic: "sequence selection iteration",
		},
		{
			question: "What type of value records the number of times a process is carried out, terminating the loop when it reaches a certain value?",
			answer: "count",
			answerType: "exact",
			topic: "count and rogue values",
		},
		{
			question: "What type of value falls outside the range of possible values for the data that is being processed, and is often used as a terminating condition?",
			answer: "rogue",
			answerType: "exact",
			topic: "count and rogue values",
		},
		{
			question: "Fill in the gap: input, _____, output",
			answer: "processing",
			answerType: "exact",
			topic: "input processing output",
		},
		{
			question: "Fill in the gap: _____, processing, output",
			answer: "input",
			answerType: "exact",
			topic: "input processing output",
		},
		{
			question: "Fill in the gap: input, processing, _____",
			answer: "output",
			answerType: "exact",
			topic: "input processing output",
		},
		{
			question: "What is the object oriented construct that inherits from a superclass?",
			answer: "subclass",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the object oriented construct that a subclass inherits from?",
			answer: "superclass",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the object oriented construct that is used as a 'plan' or 'template' for creating objects in a progam?",
			answer: "class",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is another word for a 'class instance'?",
			answer: "object",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the name given to a procedure associated with an object?",
			answer: "method",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the name given to a variable that is bound to an object?",
			answer: "instance variable",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the object oriented construct that involves wrapping variables and methods inside a class?",
			answer: "encapsulation",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the object oriented construct that involves hiding non-essential features (as private variables) and showing essential features?",
			answer: "abstraction",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the object oriented construct that allows a class to use properties and methods of an existing class?",
			answer: "inheritance",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What is the object oriented construct that allows methods to act differently based on the object performing the action?",
			answer: "polymorphism",
			answerType: "exact",
			topic: "object oriented programming",
		},
		{
			question: "What type of variable is defined within a sub routine and is hence only accessible from within that same sub routine?",
			answer: "local",
			answerType: "exact",
			topic: "local and global variables",
		},
		{
			question: "What type of variable is defined globally and is hence accessible from anywhere within a program?",
			answer: "global",
			answerType: "exact",
			topic: "local and global variables",
		},
		{
			question: "What is the name given to where in a program a variable can be accessed?",
			answer: "scope",
			answerType: "exact",
			topic: "local and global variables",
		},
		{
			question: "What is the name given to the identifier (name) of a variable reflecting the data being stored in it?",
			answer: [["self-documenting", "self documenting"]],
			answerType: "match",
			required: 1,
			topic: "self-documenting identifiers and annotation",
		},
		{
			question: "What is the name given to adding comments to a program based on what is being done?",
			answer: "annotation",
			answerType: "exact",
			topic: "self-documenting identifiers and annotation",
		},
		{
			question: "What type of variable has a lifespan that lasts the entire time that program is running?",
			answer: "static",
			answerType: "exact",
			topic: "static and dynamic variables",
		},
		{
			question: "What type of variable is assigned a new location in memory each time one is defined, and has a lifespan that ends when the sub procedure in which it was defined ends?",
			answer: "dynamic",
			answerType: "exact",
			topic: "static and dynamic variables",
		},
	],
	html: [
		// component 2
		{
			question: "Which HTML tag delineates the start of the webpage?",
			answer: "<html>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of the document's header?",
			answer: "<head>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of the document's body?",
			answer: "<body>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of a paragraph element?",
			answer: "<p>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of an italicised text element?",
			answer: "<i>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of a bold text element?",
			answer: "<b>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of an underlined text element?",
			answer: "<u>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of an element that is aligned to the centre?",
			answer: "<center>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of a large heading?",
			answer: "<h1>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: 'Which HTML tag delineates the start of an anchor for a hyperlink? <i>(assume the destination of the hyperlink is "URL")</i>',
			answer: '<a href="URL">',
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of an unordered list?",
			answer: "<ul>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of a list item?",
			answer: "<li>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of a blockquote?",
			answer: "<blockquote>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates the start of a title element (displayed as the tab name in the browser)?",
			answer: "<title>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: "Which HTML tag delineates a horizontal rule?",
			answer: "<hr>",
			answerType: "exact",
			topic: "HTML tags",
		},
		{
			question: 'Which HTML tag delineates an image element? <i>(assume the image address is "URL")</i>',
			answer: '<img src="URL">',
			answerType: "exact",
			topic: "HTML tags",
		},
	],
	greenfoot: [
		// component 2
		{
			question: "How can you get a random number between 0 and 3 in Greenfoot?",
			answer: "Greenfoot.getRandomNumber(4)",
			answerType: "exact",
			topic: "greenfoot enemy movement",
			caseSensitive: true,
		},
		{
			question: "How can you set the location of an actor in Greenfoot?",
			answer: "setLocation()",
			answerType: "exact",
			topic: "greenfoot player movement",
			caseSensitive: true,
		},
		{
			question: "How can you get the x value of an actor in Greenfoot?",
			answer: "getX()",
			answerType: "exact",
			topic: "greenfoot player movement",
			caseSensitive: true,
		},
		{
			question: "How can you set the rotation of an actor in Greenfoot?",
			answer: "setRotation()",
			answerType: "exact",
			topic: "greenfoot player movement",
			caseSensitive: true,
		},
		{
			question: "How can you move an actor one tile forward in Greenfoot?",
			answer: "move(1)",
			answerType: "exact",
			topic: "greenfoot enemy movement",
			caseSensitive: true,
		},
		{
			question: "How can you turn an actor 90 degrees in Greenfoot?",
			answer: "turn(90)",
			answerType: "exact",
			topic: "greenfoot enemy movement",
			caseSensitive: true,
		},
		{
			question: "How can you check if the right key is down in Greenfoot?",
			answer: 'Greenfoot.isKeyDown("right")',
			answerType: "exact",
			topic: "greenfoot player movement",
			caseSensitive: true,
		},
		{
			question: "How can you check if an actor of the class 'Wombat' is being touched by an actor in Greenfoot?",
			answer: "isTouching(Wombat.class)",
			answerType: "exact",
			topic: "greenfoot removing enemy",
			caseSensitive: true,
		},
		{
			question: "How can you remove an actor of the class 'Wombat' being touched by an actor in Greenfoot?",
			answer: "removeTouching(Wombat.class)",
			answerType: "exact",
			topic: "greenfoot removing enemy",
			caseSensitive: true,
		},
		{
			question: 'How can you create a sound variable called "mySound" from the sound file "sound.wav" in Greenfoot?',
			answer: 'GreenfootSound mySound = new GreenfootSound("sound.wav")',
			answerType: "exact",
			topic: "greenfoot sound",
			extraTime: 0.5, // half speed
			caseSensitive: true,
		},
		{
			question: 'How can you play the sound at the variable "mySound" in Greenfoot?',
			answer: "mySound.play()",
			answerType: "exact",
			topic: "greenfoot sound",
			caseSensitive: true,
		},
		{
			question: 'How can you get the world of class "WombatWorld" in Greenfoot and save it to a variable called "world"?',
			answer: "WombatWorld world = (WombatWorld)getWorld()",
			answerType: "exact",
			topic: "greenfoot counter and inheritance",
			extraTime: 0.5, // half speed
			caseSensitive: true,
		},
		{
			question: "How can you create a variable of class 'Counter' called 'myCounter'?",
			answer: "Counter myCounter = new Counter()",
			answerType: "exact",
			topic: "greenfoot counter and inheritance",
			caseSensitive: true,
		},
		{
			question: 'How can you set the image of an actor, where:<ul><li>The text is "hello world"</li><li>The font size is 30</li><li>The text colour is white</li><li>The background colour is blue</li></ul>',
			answer: 'setImage(new GreenfootImage("hello world", 30, java.awt.Color.WHITE, java.awt.Color.BLUE))',
			answerType: "exact",
			topic: "greenfoot counter and inheritance",
			extraTime: 0.25, // quarter speed
			caseSensitive: true,
		},
		{
			question: 'Given the world variable "world", how can you call the world function "getCounter"?',
			answer: "world.getCounter()",
			answerType: "exact",
			topic: "greenfoot counter and inheritance",
			caseSensitive: true,
		},
		{
			question: 'Given the Counter variable "counter", how can you call the Counter function "increment" with the parameter 1?',
			answer: "counter.increment(1)",
			answerType: "exact",
			topic: "greenfoot counter and inheritance",
			caseSensitive: true,
		},
	],
	assembly: [
		// component 2
		{
			question: "Which assembly language mnemonic inputs a value and stores it in the accumulator?",
			answer: "INP",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic displays the contents of the accumulator?",
			answer: "OUT",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic transfers a number from the accumulator to a RAM address?",
			answer: "STA",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic transfers a number from a RAM address to the accumulator?",
			answer: "LDA",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic adds the contents of the accumulator to the contents of a RAM address?",
			answer: "ADD",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic subtracts the contents of the accumulator from the contents of a RAM address?",
			answer: "SUB",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic jumps to the specified RAM location (is used for loops)?",
			answer: "BRA",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic stops the processor?",
			answer: "HLT",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
		{
			question: "Which assembly language mnemonic defines a variable (used at the end of the program)? The variable's name is the preceding string.",
			answer: "DAT",
			answerType: "exact",
			topic: "assembly language",
			caseSensitive: true,
		},
	],
	algorithms: [
		// component 2
		{
			question: "Which flowchart symbol defines a start/stop of a procedure? <br> A: <img src='./assets/startStop.PNG'> <br> B: <img src='./assets/decision.PNG'> <br> C: <img src='./assets/inputOutput.PNG'> <br> D: <img src='./assets/operation.PNG'> ",
			answer: "a",
			answerType: "exact",
			topic: "flowcharts",
			suddenDeath: true,
		},
		{
			question: "Which flowchart symbol defines a decision? <br> A: <img src='./assets/connector.PNG'> <br> B: <img src='./assets/flowOfControl.PNG'> <br> C: <img src='./assets/decision.PNG'> <br> D: <img src='./assets/inputOutput.PNG'> ",
			answer: "c",
			answerType: "exact",
			topic: "flowcharts",
			suddenDeath: true,
		},
		{
			question: "Which flowchart symbol defines an input or output? <br> A: <img src='./assets/flowOfControl.PNG'> <br> B: <img src='./assets/inputOutput.PNG'> <br> C: <img src='./assets/subroutine.PNG'> <br> D: <img src='./assets/operation.PNG'> ",
			answer: "b",
			answerType: "exact",
			topic: "flowcharts",
			suddenDeath: true,
		},
		{
			question: "Which flowchart symbol defines an operation? <br> A: <img src='./assets/subroutine.PNG'> <br> B: <img src='./assets/startStop.PNG'> <br> C: <img src='./assets/inputOutput.PNG'> <br> D: <img src='./assets/operation.PNG'> ",
			answer: "d",
			answerType: "exact",
			topic: "flowcharts",
			suddenDeath: true,
		},
		{
			question: "Which flowchart symbol defines a connector? <br> A: <img src='./assets/decision.PNG'> <br> B: <img src='./assets/inputOutput.PNG'> <br> C: <img src='./assets/connector.PNG'> <br> D: <img src='./assets/startStop.PNG'> ",
			answer: "c",
			answerType: "exact",
			topic: "flowcharts",
			suddenDeath: true,
		},
		{
			question: "Which flowchart symbol defines a store/subroutine call? <br> A: <img src='./assets/operation.PNG'> <br> B: <img src='./assets/connector.PNG'> <br> C: <img src='./assets/subroutine.PNG'> <br> D: <img src='./assets/startStop.PNG'> ",
			answer: "c",
			answerType: "exact",
			topic: "flowcharts",
			suddenDeath: true,
		},
		{
			question: "Which flowchart symbol shows flow of control? <br> A: <img src='./assets/decision.PNG'> <br> B: <img src='./assets/connector.PNG'> <br> C: <img src='./assets/operation.PNG'> <br> D: <img src='./assets/flowOfControl.PNG'> ",
			answer: "d",
			answerType: "exact",
			topic: "flowcharts",
			suddenDeath: true,
		},
		{
			question: "True or false: arrays start at index 1 in pseudocode.",
			answer: "false",
			answerType: "exact",
			topic: "pseudocode variables",
			suddenDeath: true,
		},
		{
			question: "True or false: strings start at index 1 in pseudocode.",
			answer: "true",
			answerType: "exact",
			topic: "pseudocode variables",
			suddenDeath: true,
		},
		{
			question: "How can a string variable be defined in pseudocode? Let the variable's name be 'myVariable'.",
			answer: "myVariable is string",
			answerType: "exact",
			topic: "pseudocode variables",
			caseSensitive: true,
		},
		{
			question: "How can a for loop be initiated in pseudocode? Let the count variable name be 'i', and be iterated from 1 to 30.",
			answer: "for i = 1 to 30",
			answerType: "exact",
			topic: "pseudocode iteration",
			caseSensitive: true,
		},
		{
			question: "How can a for loop be ended in pseudocode? Let the count variable name be 'i'.",
			answer: "next i",
			answerType: "exact",
			topic: "pseudocode iteration",
			caseSensitive: true,
		},
		{
			question: "How can an if statement be created in pseudocode? Let the boolean condition we are testing be called 'condition'.",
			answer: "if condition then",
			answerType: "exact",
			topic: "pseudocode selection",
			caseSensitive: true,
		},
		{
			question: "How can an if statement be terminated in pseudocode?",
			answer: "end if",
			answerType: "exact",
			topic: "pseudocode selection",
			caseSensitive: true,
		},
		{
			question: "How can an input be taken to the variable 'userInput' in pseudocode?",
			answer: "input userInput",
			answerType: "exact",
			topic: "pseudocode variables",
			caseSensitive: true,
		},
		{
			question: "How can an output from the variable 'variableOutput' be given in pseudocode?",
			answer: "output variableOutput",
			answerType: "exact",
			topic: "pseudocode variables",
			caseSensitive: true,
		},
		{
			question: "How should a subroutine be declared in pseudocode? Let the subroutine name be 'MySubroutine'.",
			answer: "Declare MySubroutine",
			answerType: "exact",
			topic: "pseudocode subroutines",
			caseSensitive: true,
		},
		{
			question: "How should a subroutine be terminated in pseudocode?",
			answer: "End Subroutine",
			answerType: "exact",
			topic: "pseudocode subroutines",
			caseSensitive: true,
		},
		{
			question: "How should a subroutine be called in pseudocode? Let the pseudocode's name be 'MySubroutine'.",
			answer: "call MySubroutine",
			answerType: "exact",
			topic: "pseudocode subroutines",
			caseSensitive: true,
		},
		{
			question: "List all <strong>four</strong> main data types in pseudocode.",
			answer: ["integer", "character", "string", "boolean"],
			answerType: "match",
			required: 4,
			topic: "pseudocode variables",
			caseSensitive: true,
		},
		{
			question: "How can the length of a string be found in pseudocode? Let the variable's name be 'myVariable'.",
			answer: "len(myVariable)",
			answerType: "exact",
			topic: "pseudocode string handling",
			caseSensitive: true,
		},
		{
			question: "How can a substring (midstring) be taken of a string in pseudocode? Let the string's name be 'string', the length of the substring be 'length', and the offset index be 'start'.",
			answer: "mid(string, start, length)",
			answerType: "exact",
			topic: "pseudocode string handling",
			caseSensitive: true,
			extraTime: 0.75, // more time
		},
		{
			question: "How can all instances of a substring in a string be replaced with something else in pseudocode? Let the string's name be 'string', the thing to be replaced be 'replace', and the thing for it to be replaced with be 'new'.",
			answer: "Replace(string, replace, new)",
			answerType: "exact",
			topic: "pseudocode string handling",
			caseSensitive: true,
			extraTime: 0.75, // more time
		},
		{
			question: "How can two strings be compared in pseudocode? Let the strings' names be 'str1' and 'str2'.",
			answer: "strComp(str1, str2)",
			answerType: "exact",
			topic: "pseudocode string handling",
			caseSensitive: true,
			extraTime: 0.75, // more time
		},
	],
};
