// make sure the answers are all in lower case

// user answers are not case sensitive
// exact question: user must enter the exact answer - answer must be a string
// match question: user must enter the answer word within their answer - answer must be an array
// required: number of keywords required for match question (any over this they are given extra points for)

var topics = ["hardware", "logic", "communication", "data", "software", "misc", "security", "impacts"];

var data  = {
	hardware: [
		{
			question: "I need a storage device that has a high capacity, is small, and will not likely break. <br> A: Optical storage <br> B: ROM <br> C: Magnetic storage <br> D: Solid-state storage",
			answer: "d",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "I need a storage device that is portable, cheap, and cannot be overwritten. <br> A: Magnetic storage <br> B: Optical storage <br> C: Solid-state storage <br> D: Pen-and-paper storage",
			answer: "b",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "I need a storage device that has a high capacity, is fast to access, and is cheap to manufacture. <br> A: Solid-state storage <br> B: RAM <br> C: Magnetic storage <br> D: Optical storage",
			answer: "c",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "Which is <strong>not</strong> an example of a device which uses embedded systems? <br> A: Wi-fi router <br> B: Microwave oven <br> C: Laptop <br> D: Blood pressure reader",
			answer: "c",
			answerType: "exact",
			topic: "embedded systems",
		},
		{
			question: "Why are embedded systems used? <i>more answers give you more points</i>",
			answer: ["size", "cost", "cheap", "automatic"],
			answerType: "match",
			required: 1,
			topic: "embedded systems",
		},
		{
			question: "Which is <strong>not</strong> required for <strong>all</strong> computer systems? <br> A: Screen <br> B: Operating system <br> C: Motherboard <br> D: Memory",
			answer: "a",
			answerType: "exact",
			topic: "misc hardware",
		},
		{
			question: "What are the factors that affect the performance of my CPU? <i>more answers give you more points</i>",
			answer: ["cache","clock speed","number of cores"],
			answerType: "match",
			required: 1,
			topic: "cpu cycle",
		},
		{
			question: "What are the <strong>two</strong> types of processors?",
			answer: ["risc","cisc"],
			answerType: "match",
			required: 2,
			topic: "risc and cisc",
		},
		{
			question: "What are the <strong>two</strong> parts of an instruction?",
			answer: ["opcode","operand"],
			answerType: "match",
			required: 2,
			topic: "cpu cycle",
		},
		{
			question: "What are the <strong>three</strong> parts of a CPU cycle?",
			answer: ["fetch","decode","execute"],
			answerType: "match",
			required: 3,
			topic: "cpu cycle",
		},
		{
			question: "What is hardware?",
			answer: ["physical"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "What are the registers of a CPU (their abbreviations)? <i>more answers give you more points</i>",
			answer: ["acc","mar","mdr","pc"],
			answerType: "match",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "What are the <strong>four</strong> components of a CPU?",
			answer: ["arithmetic logic unit", "registers", "internal memory", "control unit"],
			answerType: "match",
			required: 4,
			topic: "cpu architecture",
		},
		{
			question: "What is the fastest to access type of data storage in the CPU?",
			answer: ["register"],
			answerType: "match",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "Which part of the CPU is represented by: <img src='./assets/alu.PNG'>? <br> A: Arithmetic logic unit <br> B: Register <br> C: Bus <br> D: Control unit",
			answer: "a",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "Which part of the CPU is represented by: <img src='./assets/register.PNG'>? <br> A: Arithmetic logic unit <br> B: Register <br> C: Bus <br> D: Control unit",
			answer: "b",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "Which part of the CPU is represented by: <img src='./assets/cu.PNG'>? <br> A: Arithmetic logic unit <br> B: Register <br> C: Bus <br> D: Control unit",
			answer: "d",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does ALU stand for?",
			answer: "arithmetic logic unit",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does ACC stand for?",
			answer: "accumulator",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does CU stand for?",
			answer: "control unit",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does MAR stand for?",
			answer: "memory address register",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does MDR stand for?",
			answer: "memory data register",
			answerType: "exact",
			topic: "cpu architecture",
		},
		{
			question: "What does PC stand for?",
			answer: "program counter",
			answerType: "exact",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "What does RISC stand for?",
			answer: "reduced instruction set computer",
			answerType: "exact",
			topic: "risc and cisc",
		},
		{
			question: "What does CISC stand for?",
			answer: "complex instruction set computer",
			answerType: "exact",
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, uses less power and is cheaper to make?",
			answer: "risc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, runs at a faster clock speed and is larger?",
			answer: "cisc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, is often used in smartphones and tablets?",
			answer: "risc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, has a less complex clock cycle hence is more efficient at performing simpler tasks?",
			answer: "risc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which type of CPU, RISC or CISC, has a more complex clock cycle hence is more efficient at performing complex tasks?",
			answer: "cisc",
			answerType: "exact",
			suddenDeath: true,
			topic: "risc and cisc",
		},
		{
			question: "Which is <strong>not</strong> an <strong>input</strong> device? <br> A: Gyroscope <br> B: Microphone <br> C: External storage <br> D: Hard drive",
			answer: "d",
			answerType: "exact",
			topic: "input output",
		},
		{
			question: "Which is <strong>not</strong> an <strong>output</strong> device? <br> A: Monitor <br> B: Gyroscope <br> C: Speaker <br> D: Hard drive",
			answer: "b",
			answerType: "exact",
			topic: "input output",
		},
		{
			question: "What are examples of flash memory? <i>more answers give you more points</i>",
			answer: ["usb","sd","solid-state drive"],
			answerType: "match",
			required: 1,
			topic: "storage devices",
		},
		{
			question: "What must be considered when choosing a suitable secondary storage device? <i>more answers give you more points</i>",
			answer: ["capacity","speed","portability","durability","reliability","cost"],
			answerType: "match",
			required: 1,
			topic: "storage devices",
		},
		{
			question: "How is data transferred between the memory and the CPU?",
			answer: ["bus"],
			answerType: "match",
			required: 1,
			topic: "cpu architecture",
		},
		{
			question: "What are the <strong>three</strong> types of buses in a CPU?",
			answer: ["control", "address", "data"],
			answerType: "match",
			required: 3,
			topic: "cpu architecture",
		},
		{
			question: "What is the name for 4 bits? <br> A: Chomp <br> B: Byte <br> C: Bit <br> D: Nibble",
			answer: "d",
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "What is the name for 8 bits? <br> A: Chomp <br> B: Chunk <br> C: Byte <br> D: Nibble",
			answer: "c",
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "How many bytes in a kB?",
			answer: "1024",
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "How many kB in a MB?",
			answer: "1024",
			answerType: "exact",
			topic: "storage units",
		},
		{
			question: "What does RAM stand for?",
			answer: "random access memory",
			answerType: "exact",
			topic: "ram rom",
		},
		{
			question: "What does ROM stand for?",
			answer: "read only memory",
			answerType: "exact",
			topic: "ram rom",
		},
		{
			question: "What does GPU stand for?",
			answer: "graphics processing unit",
			answerType: "exact",
			topic: "misc hardware",
		},
		{
			question: "What is the place in the computer where the program and data that are currently in use are stored?",
			answer: "ram",
			answerType: "exact",
			topic: "ram rom",
		},
		{
			question: "What is the place in the computer where the programs needed to boot up the computer are stored?",
			answer: "rom",
			answerType: "exact",
			topic: "ram rom",
		},
		{
			question: "Does RAM or ROM have a higher memory capacity?",
			answer: "ram",
			answerType: "exact",
			topic: "ram rom",
		},
		{
			question: "Which type of computer memory is volatile?",
			answer: "ram",
			answerType: "exact",
			topic: "ram rom",
		},
		{
			question: "What type of storage is a hard disk? <br> A: Optical <br> B: Waterman <br> C: Magnetic <br> D: Solid-state",
			answer: "c",
			answerType: "exact",
			topic: "storage devices",
		},
		{
			question: "Which hardware component connects other components together? <i>(HINT: other components are soldered to this)</i>",
			answer: ["motherboard"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "Which hardware component provides output to your speakers? <i>(HINT: uses digital-to-analogue converter)</i>",
			answer: ["sound board"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "What is the abbreviation of the hardware component that performs massive, complex computations on large sets of data? <i>(HINT: primarily used for rendering and displaying graphics to the screen)</i>",
			answer: ["gpu"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "List some common uses of the GPU. <i>more answers give you more points</i>",
			answer: ["gaming", "data", "cryptocurrency", "render"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
	],
	logic: [
	// also includes evaluation of boolean statements
		{
			question: "What is the hardware's logic controlled by?",
			answer: ["logic gate"],
			answerType: "match",
			required: 1,
			topic: "misc hardware",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/and.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "a",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/or.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "b",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/not.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "c",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate is represented by: <img src='./assets/xor.png'>? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "d",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate has an output of 1 only if all its inputs are 1? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "a",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate has an output of 1 if any of its inputs are 1? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "b",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate has an output of 1 if its input is 0? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "c",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "Which logic gate has an output of 1 if either but not both of its inputs are 1? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "d",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "What does the symbol + mean in logical operations? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "b",
			answerType: "exact",
			topic: "logic gates",
		},
		{
			question: "What does the symbol . mean in logical operations? <br> A: AND <br> B: OR <br> C: NOT <br> D: XOR",
			answer: "a",
			answerType: "exact",
			topic: "logic gates",
		},
		// tbd: truth tables, simplify, simplification rules, simplify this with + and .
	],
	communication: [
		{
			question: "What is the name given to a collection of computers that are connected together?",
			answer: "network",
			answerType: "exact",
			topic: "networks",
		},
		{
			question: "What is the name given to a computer that is not connected to a network?",
			answer: ["stand-alone", "stand alone"],
			answerType: "match",
			required: 1,
			topic: "networks",
		},
		{
			question: "List an advantage of a network. <i>more answers give you more points</i>",
			answer: ["share", "access", "control", "security", "backup", "communication"],
			answerType: "match",
			required: 1,
			topic: "networks",
		},
		{
			question: "List a disadvantage of a network. <i>more answers give you more points</i>",
			answer: ["security", "malware", "control", "dependent", "traffic", "speed", "slow"],
			answerType: "match",
			required: 1,
			topic: "networks",
		},
		{
			question: "What does LAN stand for?",
			answer: "local area network",
			answerType: "exact",
			topic: "network types",
		},
		{
			question: "What does WAN stand for?",
			answer: "wide area network",
			answerType: "exact",
			topic: "network types",
		},
		{
			question: "What does PAN stand for?",
			answer: "personal area network",
			answerType: "exact",
			topic: "network types",
		},
		{
			question: "What type of network can be difficult to manage the security of?",
			answer: ["wide area", "wan"],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "What type of network has the greatest chance of error?",
			answer: ["wide area", "wan"],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "List a common type of PAN. <i>more answers give you more points</i>",
			answer: ["bluetooth", "usb"],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "What type of network covers a small geographical area (such as a building or small site of buildings)?",
			answer: ["local area", "lan"],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "What type of network covers a large geographical area (such as a city, country, or even several countries)?",
			answer: ["wide area", "wan"],
			answerType: "match",
			required: 1,
			topic: "network types",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/star.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "a",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/ring.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "b",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/bus.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "c",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which type of network topology is this: <img src='./assets/mesh.png'>? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "d",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "What is the result of two devices on the same network attempting to transmit data at the same time down the same connection?",
			answer: ["data collision"],
			answerType: "match",
			required: 1,
			topic: "network topology",
		},
		{
			question: "What is the name given to the physical structure of a network?",
			answer: ["topology"],
			answerType: "match",
			required: 1,
			topic: "network topology",
		},
		{
			question: "I want a network topology that is cheap and easy to expand. <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "c",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "I want a network topology that is easy to monitor, audit, and find faults. <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "a",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "I want a network topology with excellent performance. <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "d",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which network topology is most expensive? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "d",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which network topology is impossible to expand without bringing the rest of the network down? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "b",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "Which network topology is reliant on a 'central node' (hence if it goes down the whole network goes down)? <br> A: Star <br> B: Ring <br> C: Bus <br> D: Mesh",
			answer: "b",
			answerType: "exact",
			topic: "network topology",
		},
		{
			question: "List a method to connect devices in a wired network. <i>more answers give you more points</i>",
			answer: ["coaxial", "twisted pair", "fibre optic", "fibre-optic"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "Which type of transmission media is fastest but also most expensive?",
			answer: ["fibre optic", "fibre-optic"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "Which type of transmission media is most commonly used in ethernet?",
			answer: ["coaxial"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "What is the main cause of errors in wired networks?",
			answer: ["interference"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "What is the name for a digit that can be used to verify that there have been no errors in data transmission?",
			answer: ["checksum"],
			answerType: "match",
			required: 1,
			topic: "wired and wireless",
		},
		{
			question: "What does NIC stand for?",
			answer: "network interface controller",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What is the abbreviation for the piece of hardware installed into a computer to allow it to be connected to a wired network?",
			answer: "nic",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What is the name given to the unique identifier assigned to the NIC?",
			answer: "mac address",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What does WNIC stand for?",
			answer: "wireless network interface controller",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "What is the abbreviation for the piece of hardware installed into a computer to allow it to be connected to a wireless network?",
			answer: "wnic",
			answerType: "exact",
			topic: "wired and wireless",
		},
		{
			question: "Which type of network (wired or wireless) is generally faster?",
			answer: ["wired"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "wired and wireless",
		},
		{
			question: "Which type of network (wired or wireless) is generally less secure (easier to intercept)?",
			answer: ["wireless"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "wired and wireless",
		},
		{
			question: "What is a 'set of rules that govern network operations' known as?",
			answer: "protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "List the abbreviation of a common protocol or protocol family. <i>more answers give you more points</i>",
			answer: ["tcp", "ip", "http", "https", "ftp", "pop", "imap", "smtp", "wi-fi", "ethernet"],
			answerType: "match",
			required: 1,
			topic: "protocols",
		},
		{
			question: "What does TCP stand for?",
			answer: "transmission control protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does HTTP stand for?",
			answer: "hypertext transfer protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does HTTPS stand for?",
			answer: "hypertext transfer protocol secure",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does FTP stand for?",
			answer: "file transfer protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does POP stand for?",
			answer: "post office protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does IMAP stand for?",
			answer: "internet message access protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "What does SMTP stand for?",
			answer: "simple mail transfer protocol",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which <strong>three</strong> protocols (their abbreviations) are used to transmit files across a network?",
			answer: ["tcp", "ip", "ftp"],
			answerType: "match",
			required: 3,
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used by web browsers to access websites by communicating with a web server</li><li>Does not encrypt and decrypt data sent/received</li></ul>",
			answer: "http",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used by web browsers to access websites by communicating with a web server</li><li>Encrypts and decrypts data sent/received</li></ul>",
			answer: "https",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used to retrieve emails from a server</li><li>Deletes the emails from the server once they have been downloaded</li></ul>",
			answer: "pop",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Is used to retrieve emails from a server</li><li>Does not delete the emails from the server until the user deletes them</li></ul>",
			answer: "imap",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which protocol (its abbreviation): <ul><li>Governs the sending of emails using a network</li></ul>",
			answer: "smtp",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which family of protocols standardise wireless communications?",
			answer: "wi-fi",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which family of protocols standardise wired communications?",
			answer: "ethernet",
			answerType: "exact",
			topic: "protocols",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with collecting and distributing data</li><li>Makes sure data is in a suitable format for transmission</li></ul>",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with establishing and terminating connections between devices on a network (through the use of a router)</li><li>Performs error detection and correction functions</li></ul>",
			answer: ["transport"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with establishing and terminating the route to the destination of the data packet</li></ul>",
			answer: ["network"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Is concerned with the transmission media that is used to send data over a local network</li><li>Converts the data to an appropriate format for the transmission media</li></ul>",
			answer: ["physical"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer: <ul><li>Drives the physical transmission of electrical signals across the network</li></ul>",
			answer: ["data link"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer is where programs that use the network are operated?",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "Which TCP/IP layer is most abstract?",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "tcp/ip",
		},
		{
			question: "What are the three elements of a packet?",
			answer: ["header", "payload", "trailer"],
			answerType: "match",
			required: 3,
			topic: "switching",
		},
		{
			question: "Does packet switching or circuit switching ensure the data packets arrive in order at the location?",
			answer: ["circuit"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "Does packet switching or circuit switching allow multiple packets to be sent over the network at the same time?",
			answer: ["packet"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "Does packet switching or circuit switching still work if a computer on the network fails?",
			answer: ["packet"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "switching",
		},
		{
			question: "What are the two types of routing?",
			answer: ["dynamic", "static"],
			answerType: "match",
			required: 2,
			topic: "routing",
		},
		{
			question: "Does dynamic routing or static routing allow congested parts of the network to be avoided?",
			answer: ["dynamic"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "routing",
		},
		{
			question: "Is dynamic routing or static routing more straightforward to implement?",
			answer: ["static"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "routing",
		},
		{
			question: "Does dynamic routing or static routing involve data packets taking different routes rather than following a pre-set path?",
			answer: ["dynamic"],
			answerType: "match",
			required: 1,
			suddenDeath: true,
			topic: "routing",
		},
		{
			question: "Which type of network is the Internet an example of? <br> A: LAN <br> B: WAN <br> C: PAN <br> D: CAN",
			answer: "b",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is the name given to the collection of web pages we access using the Internet?",
			answer: "world wide web",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is assigned to a device every time it connects to the internet (given to devices using the Internet Protocol)?",
			answer: "ip address",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "Where are IP addresses stored?",
			answer: ["server"],
			answerType: "match",
			required: 1,
			topic: "internet",
		},
		{
			question: "What does DNS stand for?",
			answer: "domain name system",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is the name given to a collection of web pages that we may want to view?",
			answer: ["domain"],
			answerType: "match",
			required: 1,
			topic: "internet",
		},
		{
			question: "What keeps a directory of all the domain names along with their IP addresses?",
			answer: "dns",
			answerType: "exact",
			topic: "internet",
		},
		{
			question: "What is the system that means we do not need to remember the IP address to a website (only the domain name)?",
			answer: "dns",
			answerType: "exact",
			topic: "internet",
		},
		// tbd: network topologies, wired and wireless, network types
	],
	data: [
	// also includes hex, binary, denary conversion, addition of binary
	// tbd: binary shift
		{
			question: "What error is given when the total from adding binary numbers cannot be stored within a byte of data? <br> A: Logical error <br> B: Overflow error <br> C: Stack error <br> D: Binary error",
			answer: "b",
			answerType: "exact",
			topic: "errors",
		},
		{
			question: "What information does metadata store for images? <i>more answers give you more points</i>",
			answer: ["dimension", "resolution", "compression", "depth", "colour", "author", "time", "date", "creator", "purpose", "size", "source", "quality", "location"],
			answerType: "match",
			required: 1,
			topic: "image files",
		},
		{
			question: "List an example of a character set. <i>more answers give you more points</i>",
			answer: ["ascii", "unicode", "iso"],
			answerType: "match",
			required: 1,
			topic: "text files",
		},
		{
			question: "What is the measurement of sampling rate?",
			answer: ["hertz", "hz"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Which <strong>three</strong> factors affect file size of a sound file?",
			answer: ["length", "sample rate", "sampling rate", "resolution"],
			answerType: "match",
			required: 3,
			topic: "sound files",
		},
		{
			question: "Which factors can affect quality of a sound file's playback? <i>more answers give you more points</i>",
			answer: ["sample rate", "sampling rate", "resolution"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "What data type is '3.4'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '2.0'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '2'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "a",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is 'true'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "c",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is 'V'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "d",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '@'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "d",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is 'Computer science is fun!'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "e",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is ['Bob', 'Jane', 'Bill']? <br> A: String <br> B: One-dimensional string array <br> C: Two-dimensional string array <br> D: Three-dimensional string array",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What data type is '@'? <br> A: Integer <br> B: Real <br> C: Boolean <br> D: Character <br> E: String",
			answer: "d",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What is the name of an array that does not have a fixed length?",
			answer: ["dynamic"],
			answerType: "match",
			required: 1,
			topic: "data types",
		},
		{
			question: "What is the name of an array that has a fixed length?",
			answer: ["static"],
			answerType: "match",
			required: 1,
			topic: "data types",
		},
		{
			question: "Which is an array of different data types? <br> A: Table <br> B: Record <br> C: Field <br> D: Database",
			answer: "b",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "Which is an array of the same data type? <br> A: Table <br> B: Record <br> C: Field <br> D: Database",
			answer: "c",
			answerType: "exact",
			topic: "data types",
		},
		{
			question: "What is the name of the process that checks to ensure that data entered is reasonable and sensible?",
			answer: "validation",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "List a common validation rule that can be used. <i>more answers give you more points</i>",
			answer: ["length", "range", "type", "format", "presence"],
			answerType: "match",
			required: 1,
			topic: "validation",
		},
		{
			question: "Which validation rule checks that the data entered contains a set number of characters? <br> A: Length check <br> B: Range check <br> C: Type check <br> D: Format check <br> E: Presence check",
			answer: "a",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "Which validation rule checks that the data is of a certain data type? <br> A: Length check <br> B: Range check <br> C: Type check <br> D: Format check <br> E: Presence check",
			answer: "c",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "Which validation rule checks that data has been entered into the input box? <br> A: Length check <br> B: Range check <br> C: Type check <br> D: Format check <br> E: Presence check",
			answer: "e",
			answerType: "exact",
			topic: "validation",
		},
		{
			question: "What is the name of the process that checks data entered into the system matches data from the source document?",
			answer: "verification",
			answerType: "exact",
			topic: "verification",
		},
		{
			question: "List a common verification method that can be used. <i>more answers give you more points</i>",
			answer: ["double keying", "proofreading"],
			answerType: "match",
			required: 1,
			topic: "verification",
		},
	],
	software: [
		{
			question: "Which type of software controls the operation of hardware in a computer?",
			answer: ["system"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of software is the everyday programs that we use to create documents and perform tasks?",
			answer: ["application"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of software provides a platform to run applications software?",
			answer: ["system"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "List a type of system software. <i>more answers give you more points</i>",
			answer: ["device driver", "utility software", "operating system", "os"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of system software: <ul><li>Is loaded by the computer after the initial boot-up</li><li>Controls the operations of the hardware</li><li>Manages all other software</li></ul>",
			answer: ["operating system", "os"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which type of system software: <ul><li>Helps to manage, maintain, and control the computer's resources</li></ul>",
			answer: "utility software",
			answerType: "exact",
			topic: "misc software",
		},
		{
			question: "Which type of system software: <ul><li>Controls a particular device connected to a computer system</li><li>Is controlled by the operating system</li></ul>",
			answer: "device driver",
			answerType: "exact",
			topic: "misc software",
		},
		{
			question: "Give a role of the operating system. <i>more answers give you more points</i>",
			answer: ["user interface", "memory", "multitask", "peripheral", "drivers", "user", "file", "processes"],
			answerType: "match",
			required: 1,
			topic: "operating system",
		},
		{
			question: "<strong>True</strong> or <strong>false</strong>: a computer cannot be used without an operating system.",
			answer: "true",
			answerType: "exact",
			suddenDeath: true,
			topic: "operating system",
		},
		{
			question: "What does GUI stand for?",
			answer: "graphical user interface",
			answerType: "exact",
			topic: "interfaces",
		},
		{
			question: "What does CLI stand for?",
			answer: "command line interface",
			answerType: "exact",
			topic: "interfaces",
		},
		{
			question: "What does NLI stand for?",
			answer: "natural language interface",
			answerType: "exact",
			topic: "interfaces",
		},
		{
			question: "Give a common example of an NLI. <i>more answers give you more points</i>",
			answer: ["siri", "alexa", "cortana", "google assistant"],
			answerType: "match",
			required: 1,
			topic: "interfaces",
		},
		{
			question: "Give a common example of a peripheral. <i>more answers give you more points</i>",
			answer: ["mouse", "keyboard", "microphone", "printer", "scanner", "monitor", "touchscreen", "camera"],
			answerType: "match",
			required: 1,
			topic: "peripherals",
		},
		{
			question: "Which is NOT a peripheral? <br> A: Mouse <br> B: Printer <br> C: Hard drive <br> D: USB stick",
			answer: "c",
			answerType: "exact",
			topic: "peripherals",
		},
		{
			question: "Give a task that utility software may be responsible for. <i>more answers give you more points</i>",
			answer: ["file conversion", "file repair", "compression", "backup", "encryption", "defragmentation", "antivirus"],
			answerType: "match",
			required: 1,
			topic: "misc software",
		},
		{
			question: "Which is the sequence of bits used to encrypt or decrypt data? <br> A: Encryption key <br> B: Encryption algorithm <br> C: Plain text <br> D: Cypher text",
			answer: "a",
			answerType: "exact",
			topic: "encryption",
		},
		{
			question: "Which type of encryption uses the same encryption key to encrypt and decrypt the data?",
			answer: ["symmetric"],
			answerType: "match",
			required: 1,
			topic: "encryption",
		},
		{
			question: "Which type of encryption uses a different encryption key to encrypt and decrypt the data?",
			answer: ["asymmetric"],
			answerType: "match",
			required: 1,
			topic: "encryption",
		},
		{
			question: "Which stage of the encryption/decryption process is a <strong>private key</strong> used for in asymmetric encryption?",
			answer: ["decrypt"],
			answerType: "match",
			required: 1,
			topic: "encryption",
		},
		{
			question: "Which type of backup only backs up files that have changed since the last backup was carried out?",
			answer: ["incremental"],
			answerType: "match",
			required: 1,
			topic: "backup",
		},
	],
	// topics that are small enough to not be worth their own section
	misc: [
		// principles of programming
		{
			question: "List a high-level language. <i>more answers give you more points</i>",
			answer: ["visual basic", "python", "javascript", "java", "c#", "c++", "go", "lisp", "scala", "ruby"],
			answerType: "match",
			required: 1,
			topic: "programming languages",
		},
		{
			question: "List a low-level language. <i>more answers give you more points</i>",
			answer: ["assembly", "machine"],
			answerType: "match",
			required: 1,
			topic: "programming languages",
		},
		{
			question: "List a benefit of low-level languages. <i>more answers give you more points</i>",
			answer: ["speed", "control"],
			answerType: "match",
			required: 1,
			topic: "programming languages",
		},
		// software engineering
		{
			question: "What does IDE stand for?",
			answer: "integrated development environment",
			answerType: "exact",
			topic: "software engineering",
		},
		{
			question: "List a feature of an IDE. <i>more answers give you more points</i>",
			answer: ["code editor", "runtime environment", "error diagnostics"],
			answerType: "match",
			required: 1,
			topic: "software engineering",
		},
		{
			question: "List a way to debug a program using an IDE. <i>more answers give you more points</i>",
			answer: ["trace", "break point", "memory inspection"],
			answerType: "match",
			required: 1,
			topic: "software engineering",
		},
		// program construction
		{
			question: "List a type of translator. <i>more answers give you more points</i>",
			answer: ["compiler", "interpreter", "assembler"],
			answerType: "match",
			required: 1,
			topic: "translators",
		},
		{
			question: "Which type of translator translates one line at a time?",
			answer: "interpreter",
			answerType: "exact",
			topic: "translators",
		},
		{
			question: "Which type of translator translates all lines at once?",
			answer: "compiler",
			answerType: "exact",
			topic: "translators",
		},
		{
			question: "Which type of translator translates assembly language?",
			answer: "assembler",
			answerType: "exact",
			topic: "translators",
		},
		{
			question: "Which type of translator produces an executable file with runs the program?",
			answer: "compiler",
			answerType: "exact",
			topic: "translators",
		},
		{
			question: "List a stage involved in the compilation process. <i>more answers give you more points</i>",
			answer: ["lexical analysis", "symbol table construction", "syntax analysis", "semantic analysis", "code generation", "optimisation"],
			answerType: "match",
			required: 1,
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves removing white space?",
			answer: "lexical analysis",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves storing variable and subroutine names?",
			answer: "symbol table construction",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves checking the syntax is correct?",
			answer: "syntax analysis",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves checking variable types?",
			answer: "semantic analysis",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves converting the code into object code (understood by computer)?",
			answer: "code generation",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "Which compilation stage involves making the program run better on the processor?",
			answer: "optimisation",
			answerType: "exact",
			topic: "compilation process",
		},
		{
			question: "List a type of error that can occur during programming. <i>more answers give you more points</i>",
			answer: ["syntax", "logic", "runtime", "linking", "rounding", "truncation"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is caused by division by 0?",
			answer: ["runtime"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is caused by division by incorrect parameters for a subroutine?",
			answer: ["runtime"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
		{
			question: "Which error is thrown before the program runs?",
			answer: ["syntax"],
			answerType: "match",
			required: 1,
			topic: "errors",
		},
	],
	security: [
		{
			question: "What are the <strong>two</strong> categories of danger that exist when storing personal data on computers?",
			answer: ["accidental", "malicious"],
			answerType: "match",
			required: 2,
			topic: "data protection",
		},
		{
			question: "How can personal data be protected? <i>more answers give you more points</i>",
			answer: ["hash", "password", "access level", "encryption"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "What is the name given to the process that reduces a file's size for efficient storage and transmission?",
			answer: "compression",
			answerType: "exact",
			topic: "compression",
		},
		// maybe make a function for the following 2?
		{
			question: "Find the file size of a sound file that is 10 seconds long, has a 150Hz sample rate, and has an 8 bit sample resolution. Give your answer in bytes.",
			answer: "1500",
			answerType: "exact",
			topic: "sound files",
		},
		{
			question: "Find the file size of a sound file that is 10 seconds long, has a 100Hz sample rate, and has an 4 bit sample resolution. Give your answer in bits.",
			answer: "4000",
			answerType: "exact",
			topic: "sound files",
		},
		{
			question: "What is a positive of a lossless file format?",
			answer: ["quality"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "What is a negative of a lossless file format?",
			answer: ["size"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Give a common example of a lossless sound file format. <i>more answers give you more points</i>",
			answer: ["wav", "aiff", "flac", "alac", "ape"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Give a common example of a lossy sound file format. <i>more answers give you more points</i>",
			answer: ["mp3", "aac", "vorbis", "wma"],
			answerType: "match",
			required: 1,
			topic: "sound files",
		},
		{
			question: "Which best describes 'malware'? <br> A: A program that speeds up a computer's processing speed <br> B: Illegally downloaded media <br> C: A program designed to do harm to a computer or its data <br> D: A program that is downloaded from an email attachment ",
			answer: "c",
			answerType: "exact",
			topic: "malware",
		},
		{
			question: "List a common example of malware. <i>more answers give you more points</i>",
			answer: ["virus", "worm", "trojan", "keylogger", "key logger", "adware"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Infiltrates a computer system and replicates itself</li><li>Requires human involvement to duplicate</li><li>Causes damage by corrupting data or usingup all available memory</li></ul>",
			answer: ["virus"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Infiltrates a computer system and replicates itself</li><li>Does not require human involvement to duplicate</li><li>Causes damage by corrupting data or usingup all available memory</li></ul>",
			answer: ["worm"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Is disguised as a harmless file or download</li></ul>",
			answer: ["trojan"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Records keypresses from a user on a computer</li><li>Can pick out personal and sensitive data (such as passwords)</li></ul>",
			answer: ["keylogger", "key logger"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "Which type of malware: <ul><li>Injects adverts into pages and programs on a computer</li><li>May come with other types of malware</li></ul>",
			answer: ["adware"],
			answerType: "match",
			required: 1,
			topic: "malware",
		},
		{
			question: "List a way companies can protect themselves against malware and its impacts. <i>more answers give you more points</i>",
			answer: ["acceptable use policy", "disaster recovery policy", "anti-malware", "penetration testing"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which type of policy stipulates what users of a network may and may not do with that network?",
			answer: ["acceptable use"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which type of policy describes how a company would aim to recover from catastrophic damage to hardware, software, or data?",
			answer: ["disaster recovery"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "Which best describes 'social engineering'? <br> A: Designing and building areas for socialisation <br> B: Convincing people not to download malware <br> C: Engineering with friends <br> D: Tricking people into breaking security procedures ",
			answer: "d",
			answerType: "exact",
			topic: "social engineering",
		},
		{
			question: "List a common example of social engineering. <i>more answers give you more points</i>",
			answer: ["blagging", "phishing", "fraud"],
			answerType: "match",
			required: 1,
			topic: "social engineering",
		},
		{
			question: "Which type of social engineering involves: <ul><li>Convincing someone you are someone else</li><li>Tricking them to directly give away information such as passwords</li></ul>",
			answer: ["blagging"],
			answerType: "match",
			required: 1,
			topic: "social engineering",
		},
		{
			question: "Which type of social engineering involves: <ul><li>Sending emails pretending to be a reputable company</li><li>Trying to gain personal details or install malware through this email</li></ul>",
			answer: ["phishing"],
			answerType: "match",
			required: 1,
			topic: "social engineering",
		},
		{
			question: "Which process: <ul><li>Involves employing a team of people to simulate potential attacks on their network</li><li>Reveals security weak points for a company</li></ul>",
			answer: ["penetration testing"],
			answerType: "match",
			required: 1,
			topic: "data protection",
		},
		{
			question: "List a role of Internet cookies. <i>more answers give you more points</i>",
			answer: ["preference", "advert", "login", "information"],
			answerType: "match",
			required: 1,
			topic: "cookies",
		},
	],
	impacts: [
		{
			question: "Which best describes 'ethics'? <br> A: How something works <br> B: A set of moral principles <br> C: What governments think about an issue <br> D: A fill-up for a GCSE spec ",
			answer: "b",
			answerType: "exact",
			topic: "ethical impacts",
		},
		{
			question: "List an ethical impact of technology. <i>more answers give you more points</i>",
			answer: ["privacy", "cybersecurity", "hacking", "access", "equality"],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "List a possible cause of loss of privacy due to technology. <i>more answers give you more points</i>",
			answer: ["monitoring", "interception", "distribution", "theft"],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "List a type of hacker. <i>more answers give you more points</i>",
			answer: ["white-hat", "white hat", "black-hat", "black hat", "grey-hat", "grey hat"],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "Which type of hacker is seen as most ethical?",
			answer: ["white-hat", "white hat"],
			answerType: "match",
			required: 1,
			topic: "ethical impacts",
		},
		{
			question: "Which best describes 'legislation'? <br> A: A penalty that applies to someone who breaks the law <br> B: The altering of existing law(s) by a government <br> C: Law(s) introduced by a government <br> D: Protest against a law ",
			answer: "c",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which best describes 'sanction'? <br> A: A penalty that applies to someone who breaks the law <br> B: The altering of existing law(s) by a government <br> C: Law(s) introduced by a government <br> D: Protest against a law ",
			answer: "a",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "List a type of sanction. <i>more answers give you more points</i>",
			answer: ["fine", "prison"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Limits the amount of data that an organisation is allowed to collect about a person</li><li>Governs the security of the data when it has been collected</li></ul>",
			answer: ["data protection"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "What year was the Data Protection Act passed?",
			answer: "1998",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Protects personal data held by organisations from hackers</li></ul>",
			answer: ["computer misuse"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "What year was the Computer Misuse Act passed?",
			answer: "1990",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Protects intellectual property</li></ul>",
			answer: ["copyright", "design", "patents"],
			answerType: "match",
			required: 3,
			topic: "legislation",
		},
		{
			question: "What year was the Copyright, Designs and Patents Act passed?",
			answer: "1988",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "What crime does the Copyright, Designs and Patents Act combat?",
			answer: "piracy",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "Which act relevant to computing: <ul><li>Makes it possible for the public to access information about a public organisation</li><li>Requires public organisations to publish certain data on a regular basis</li></ul>",
			answer: ["freedom of information"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "What year was the Freedom of Information Act passed?",
			answer: "2000",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "List an example of a type of public organisation. <i>more answers give you more points</i>",
			answer: ["school", "university", "parliament", "council", "police", "government", "nhs", "army"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "Which of these does not apply to a Creative Commons license? <br> A: There are many different types of the license <br> B: Work may be shared freely if under this license <br> C: Licenses provided by Creative Commons organisation <br> D: Individual must ask owner's position to use work under this license ",
			answer: "d",
			answerType: "exact",
			topic: "legislation",
		},
		{
			question: "List a type of Creative Commons license. <i>more answers give you more points</i>",
			answer: ["attribution", "share-alike", "non-commerical", "no derivative works"],
			answerType: "match",
			required: 1,
			topic: "legislation",
		},
		{
			question: "List a negative impact of technology on the environment. <i>more answers give you more points</i>",
			answer: ["waste", "pollution", "resource", "landfill", "material", "packaging"],
			answerType: "match",
			required: 1,
			topic: "environmental impacts",
		},
		{
			question: "List a positive impact of technology on the environment. <i>more answers give you more points</i>",
			answer: ["education", "communication", "research"],
			answerType: "match",
			required: 1,
			topic: "environmental impacts",
		},
		{
			question: "Which typically uses the least power? <br> A: Large monitor desktop computer <br> B: Small monitor desktop computer <br> C: Large monitor laptop computer <br> D: Small monitor laptop computer ",
			answer: "d",
			answerType: "exact",
			topic: "environmental impacts",
		},
	],
};
